### ISSUE TITLE
Refactoring: remove package_name

### ISSUE THREAD

**Issue by joerick** [joerick/cibuildwheel#102]
I noticed while looking at the code today that the `package_name` property isn't actually used anywhere. We should probably remove it, unless anyone has particular designs for it?

Also, a few of the test cases have stuff like 

```
if sys.argv[-1] != '--name':
```

which could be removed at the same time

**Comment by YannickJadoul** [comment]
Seems unnecessary, indeed.

Do you still know what it was used for, initially? To pass to `pip wheel` or ... ?

**Comment by joerick** [comment]
I think it was for picking up the correct wheel post-build, but that was solved with the --no-deps flag. I might be wrong, though

**Comment by YannickJadoul** [comment]
Then I'm OK with trashing it! :-D

**Comment by xanderyzwich** [comment]
I'm working on this

**Comment by xanderyzwich** [comment]
@joerick what branch would you like this pull request on?

**Comment by YannickJadoul** [comment]
The master branch (as you've indeed targeted in your PR) is fine!
