### ISSUE TITLE
List of build tags/identifiers matched by CIBW_BUILD and CIBW_SKIP

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#105]
I keep finding myself checking the lists of build configurations and their identifiers when adapting `CIBW_SKIP` (and now introducing `CIBW_BUILD`! ;-) )

Could/should we either add an explicit list (or table) to the README, or add a subcommand that has `cibuildwheel` list all known configurations? Or is this already documented and am I just overlooking it?

**Comment by joerick** [comment]
Good point, this should be documented somewhere. A command line option makes sense, something like `cibuildwheel --build-identifier`.

**Comment by YannickJadoul** [comment]
Fixed by `--print-build-identifiers` in #137. Closing.
