### ISSUE TITLE
OSX: open_for_csv not found in wheel.util (on delocate-list)

### ISSUE THREAD

**Issue by ysig** [joerick/cibuildwheel#106]
Hello,

although my package [builds normally on Linux under Travis](https://travis-ci.org/ysig/GraKeL/builds/435300832), [when running it on OSX](https://travis-ci.org/ysig/GraKeL/jobs/435300837) I get the strange error:

>  (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/2.7/bin/delocate-listdeps", line 12, in <module>
>     from delocate import tree_libs, wheel_libs, __version__
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/delocate/__init__.py", line 3, in <module>
>     from .delocating import delocate_path, delocate_wheel, patch_wheel
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/delocate/delocating.py", line 18, in <module>
>     from .wheeltools import rewrite_record, InWheel
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/delocate/wheeltools.py", line 14, in <module>
>     from wheel.util import urlsafe_b64encode, open_for_csv, native
> ImportError: cannot import name open_for_csv

for which I couldn't find a reference online.
Is it because a library is downgraded on OSX (as another one get's upgraded)?
Maybe `delocate` should be upgraded or `wheel`, although I don't have a clue :)
I am using the [default osx image of travis](https://docs.travis-ci.com/user/reference/osx/).

Thanks for the support and this amazingly helpful package!

**Comment by saimn** [comment]
It seems related to the recent release of wheel (0.32), which removed `open_for_csv`:
https://github.com/pypa/wheel/commit/186ca2c82a7bdcc87b0a5584528507ad404ba790#diff-7dc328f716d014fd1a19755f7d89c4e0

**Comment by YannickJadoul** [comment]
Does the latest version of `delocate` (with the latest version of `wheel`) still work on a local macOS machine?

**Comment by YannickJadoul** [comment]
Update: the latest version on delocate's master seems to be working. I quickly forked the repo and started the tests on Travis: see https://travis-ci.org/YannickJadoul/delocate/builds/435534535.

But the commit that actually contains the fix (https://github.com/matthew-brett/delocate/commit/68355ee937826e0e5db4c75833f165db670e6ba4) seems to not have been released yet? :-(

Should someone open an issue on the delocate repo?

**Comment by saimn** [comment]
I forgot to mention, there is the same error with `auditwheel` : https://github.com/pypa/auditwheel/issues/102

**Comment by YannickJadoul** [comment]
Maybe we ought to keep an eye on those issues and go for the same solution as https://github.com/pypa/manylinux/pull/229, for now, i.e. installing `wheel==0.31.1` ?

**Comment by YannickJadoul** [comment]
Please try #107, by installing `git+https://github.com/joerick/cibuildwheel.git@wheel-0.31.1` instead of the latest version of cibuildwheel on PyPI.

This branch/PR fixes the version of wheel installed to 0.31.1 for macOS (and delocate) and Linux (auditwheel in the manylinux1 image is also affected by the update).

**Comment by YannickJadoul** [comment]
Version 0.7.4 of `delocate` has been released and solves the original problem (at least for me, please confirm). Meanwhile, the `manylinux1` image has been patched to include version 0.31.1 of `wheel` until `auditwheel` gets fixed, and a new docker image is available and seems to be working as well.

If further issues remain or return, please reopen, but for now this seems to be OK again :-)
