### ISSUE TITLE
Build Error with Python 2.6 under Linux 

### ISSUE THREAD

**Issue by nabobalis** [joerick/cibuildwheel#12]
I noticed that Python 2.6 is still listed under the linux.py. I have added ```CIBW_SKIP=cp26-*``` but it doesn't seem to skip it. (Edit: that was my mistake, it skips now)

I get this build error which I assume is a problem with py26 being left in the linux.py file, as it doesn't exist in the windows or macos files.

```python
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Processing /project
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-koHRvT-build/setup.py", line 91, in <module>
        package_info = get_package_info()
      File "/tmp/pip-koHRvT-build/astropy_helpers/astropy_helpers/setup_helpers.py", line 401, in get_package_info
        ext_modules.extend(setuppkg.get_extensions())
      File "sunpy/io/setup_package.py", line 15, in get_extensions
        if platform.system() == 'Windows' or sys.version_info.major == 3:
    AttributeError: 'tuple' object has no attribute 'major'
``` 
That attribute exists for py27 and py3, so I assume that it doesn't exist for py26.

**Comment by joerick** [comment]
I just did a little audit of cibuildwheel config files on Github and most have the `CIBW_SKIP=cp26-*` option enabled - clearly most users don't want it and it's messing with a lot builds. So I agree, let's disable it.
