### ISSUE TITLE
travis-ci linux build fails

### ISSUE THREAD

**Issue by randy3k** [joerick/cibuildwheel#138]
Lately, the linux travis-ci build started to fail at my repo

https://travis-ci.org/randy3k/rchitect/builds/527826986

It has been working fine a few days ago and I cannot get it running today. It is stuck at
```
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Processing /project

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

To make sure it is not an issue caused by the new commits of myself, I also tried to rerun some of the successful builds and they failed either.

**Comment by randy3k** [comment]
Not sure if it is related to the outage of pypi https://status.python.org/

**Comment by randy3k** [comment]
I am still not able to resolve the travis linux issue. I just moved the builds to circleci and it works.

**Comment by YannickJadoul** [comment]
@randy3k Sorry for the delay in answering. I did run the `cibuildwheel` tests on my Travis yesterday, and there everything seems to be working?

https://travis-ci.org/YannickJadoul/cibuildwheel/builds/527997186

**Comment by randy3k** [comment]
I have force pushed and reran that build. See this link https://travis-ci.org/randy3k/rchitect/jobs/527956974 for the error.

**Comment by YannickJadoul** [comment]
Hmmm, this is really weird. But this time it's stuck on a Python 2.7 build, rather than the 3.4? So it's probably not related to the 3.4 deprecation.

**Comment by YannickJadoul** [comment]
I don't really know where to look to resolve this issue, to be honest. I don't know what could have changed in cibuildwheel to break things. The two suggestions I have, if you still want to investigate, are:
- Does the old version of cibuildwheel still works?
- Does a manual build with manylinux docker images work? (I just tested that, and for me it seems to work.)

But if you're happy with CircleCI, let's hope this was just a weird fluke in Travis :-)
