### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#143]
Are we interested in building PyPy wheels with `cibuildwheel`, @joerick and @mayeut? I would be. Apparently, PyPy now also offers [manylinux images with PyPy executables](https://github.com/pypy/manylinux).

I'm happy to look into this, if agreed this would be a useful addition to `cibuildwheel`. It shouldn't even be a huge effort, I'd guess. But then should also maybe have a think about whether to make this an opt-in feature, and how?

**Comment by YannickJadoul** [comment]
Hmmm, only now noticed this is for the `manylinux2010` standard, so this semi-depends on #135

**Comment by joerick** [comment]
Oooh, that looks great! Yes that feels like a logical step for `cibuildwheel`. I actually didn't realise Cpython extensions would work with Pypy, but it looks like [they support that](http://doc.pypy.org/en/latest/faq.html#do-cpython-extension-modules-work-with-pypy). I'd be happy to just add it to CIBW_BUILD by default, assuming the builds are painless enough :D

**Comment by altendky** [comment]
cpython c-api isn't the only thing to compile.  there's cffi too.

**Comment by YannickJadoul** [comment]
Definitely! And even more advisable for PyPy, as far as I know.
But of course, since the C API is now +- complete in PyPy, the first step could already just easily allow developers to target PyPy with their existing code?

Either way, I think `cibuildwheel` is quite agnostic about the underlying mechanism, or am I forgetting something?

**Comment by altendky** [comment]
Oh yes, cffi vs c-api shouldn't really matter to cibuildwheel I don't think.  I was just mentioning the other sort of project that needs binary wheels. Anyways, I would tend towards adding it to the defaults.  I think encouraging more PyPy awareness and support is a good thing.

**Comment by altendky** [comment]
fyi, https://github.com/antocuni/pypy-wheels/tree/master/docker/image

**Comment by YannickJadoul** [comment]
@altendky Thanks!
Was I just hallucinating when I thought I'd seen a ready and published `manylinux2010` image for PyPy, then, a few months ago?
