### ISSUE TITLE
Support for gitlab-CI

### ISSUE THREAD

**Issue by pmav99** [joerick/cibuildwheel#158]
https://docs.gitlab.com/ce/ci/

**Comment by Prier** [comment]
Would really like to have support for Gitlab CI.

**Comment by Czaki** [comment]
@joerick there is gitlab ci for external repositories https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/index.html

And gitlab provide runners for Linux and Windows https://docs.gitlab.com/ee/user/gitlab_com/index.html#shared-runners

So there is an option to add this support. What dou You think about this? Could you try to setup initial integration to check if it works?

**Comment by YannickJadoul** [comment]
Ow, that does seem interesting, if we could test it from here!

**Comment by joerick** [comment]
Implemented (linux-only) in #419. See #427 for an issue regarding Windows support.
