### ISSUE TITLE
Docker deprecation notice.

### ISSUE THREAD

**Issue by hameerabbasi** [joerick/cibuildwheel#166]
In my build logs I get this deprecation notice:

```
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.
```

Thought it'd be nice to report.

**Comment by YannickJadoul** [comment]
No need to worry; just something inside of docker, it seems: https://github.com/docker/distribution/issues/2976

Thanks for reporting, though! :-)
