### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by Legrandin** [joerick/cibuildwheel#170]
Python 3.8 was released on [October 14th, 2019](https://docs.python.org/3/whatsnew/3.8.html).

Can it be added to `cibuildwheel`?

**Comment by YannickJadoul** [comment]
Yessss, thanks for the reminder! Should be reasonably quick to implement, though it depends a bit on the Python versions AppVeyor and Azure are offering

**Comment by YannickJadoul** [comment]
@Legrandin, see #172 to follow progress :)

So far, it seems that Azure Pipelines and AppVeyor do not support Python 3.8 on Windows, yet.

**Comment by joerick** [comment]
Fixed in #180. Release should be within the next couple weeks...!

**Comment by MuellerSeb** [comment]
> Fixed in #180. Release should be within the next couple weeks...!

Are there any news on when to release it?

**Comment by YannickJadoul** [comment]
@MuellerSeb In the meanwhile, `pip3 install git+https://github.com/joerick/cibuildwheel.git` should work, though?

**Comment by MuellerSeb** [comment]
> @MuellerSeb In the meanwhile, `pip install git+https://github.com/joerick/cibuildwheel.git` should work, though?

Since I want to use it in CI, I'll wait for the next official release, to stick to one version.

**Comment by joerick** [comment]
I want to be sure that  #175 isn't a problem and merge #169 before release... so I can't give an exact date, but within a couple weeks :)

**Comment by MuellerSeb** [comment]
I'm cool with that. Thanks for your great work!

**Comment by YannickJadoul** [comment]
@joerick In principle, the docs don't need to be ready before release, right? Commits to `README` on the master will show up immediately on GitHub, and the readthedocs can build independently of a release?
