### ISSUE TITLE
typing module causes AttributeError on linux

### ISSUE THREAD

**Issue by djhoese** [joerick/cibuildwheel#176]
I have cibuildwheel set up to run on Azure for the vispy package. In the last couple weeks to a month we've started seeing the below exception when running our tests (pytest) but only on the linux environments:

```
Traceback (most recent call last):
  File "/opt/python/cp37-cp37m/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/cp37-cp37m/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/pytest.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/_pytest/assertion/__init__.py", line 5, in <module>
    from typing import Optional
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

It seems that the pypa docker image is installing the backport 'typing' package in environments that shouldn't need it and I've verified this locally by downloading the latest image for manylinux x86_64. I will file a bug report with them for the `typing` module existing, however I'm unable to reproduce the typing exception above on my local docker with this image and no cibuildwheel and running the tests for my package.

So I'm wondering if anyone has ideas what cibuildwheel might be doing that might cause the `typing.py` to behave differently. Custom PATH or PYTHONPATH maybe?

Note: I tested different versions of various dependencies and using older versions of cibuildwheel (<0.12) and it didn't seem to make a difference. The only thing that worked was uninstalling the `typing` package/module. Here is the pull request where I'm playing with things: https://github.com/vispy/vispy/pull/1725

**Comment by YannickJadoul** [comment]
Hmmm, that's weird. As far as I know, there's nothing in `cibuildwheel` that could be related to this.

I'll get a closer look tomorrow or the day after, but I don't believe we do anything more to the `manylinux` image that could cause this.

I've done a quick seach in the `manylinux` repository on "typing", and all I can find is this: https://github.com/pypa/manylinux/blob/52c7b5dfd817255f8ae560734a36de3b19c1bb85/docker/build_scripts/py37-requirements.txt#L13 Could this be related to your problem?

**Comment by djhoese** [comment]
Yes, that's it. I made an issue with manylinux to ask about this: https://github.com/pypa/manylinux/issues/377

What's even more odd is that this is coming from an import and should work in either the builtin typing module or the separate package typing.

What directory does cibuildwheel run from? Maybe it is a relative import issue?

**Comment by YannickJadoul** [comment]
> What directory does cibuildwheel run from? Maybe it is a relative import issue?

Not that I can imagine: the project is git-cloned, copied into the `cibuildwheel` Docker image under `/project`, and this folder is used as working directory inside of the image, as well.

Full details on what's run inside of the docker image: https://github.com/joerick/cibuildwheel/blob/ee2a90880a2d7c3a9b3ac953e2aa2ae50187e51b/cibuildwheel/linux.py#L54-L129

**Comment by YannickJadoul** [comment]
By the way, this shows that the problem is probably only Python 3.7, for which `auditwheel` is installed:

```
[root@3bb3dac57657 /]# /opt/python/cp37-cp37m/bin/pip list
Package    Version  
---------- ---------
auditwheel 2.1.1    
certifi    2019.9.11
pip        19.1.1   
pyelftools 0.25     
setuptools 41.4.0   
typing     3.7.4.1  
wheel      0.31.1   
WARNING: You are using pip version 19.1.1, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@3bb3dac57657 /]# /opt/python/cp36-cp36m/bin/pip list
Package    Version
---------- -------
pip        19.1.1 
setuptools 41.4.0 
wheel      0.31.1 
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by djhoese** [comment]
Interesting. `auditwheel` has even had a pull request to specifically remove `typing` from its requirements: https://github.com/pypa/auditwheel/pull/162

I'll play around with a few more dependencies. Something is making the `typing` package choke on itself.

**Comment by YannickJadoul** [comment]
Funnily enough, to quote https://pypi.org/project/typing/:

> [...] NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT. [...]

That doesn't seem to be true, either :-D

**Comment by djhoese** [comment]
This seems to be something with import order. If I import the same thing that pytest is importing in my pre-build commands with  `python -c 'from typing import Optional'` then I don't seem to get an error.

**Comment by djhoese** [comment]
Found this: https://github.com/python/typing/issues/573

This is exactly how we are calling it in vispy (iterate through the various vispy backends to test, run_subprocess to run pytest with that backend). So the suggested fix is to just not install typing. Closing this since it is not cibuildwheel's fault.

**Comment by YannickJadoul** [comment]
Argh, that's a bit annoying indeed. But good to know it's not `cibuildwheel`. Thanks! And good luck with the workaround!
