### ISSUE TITLE
manylinux2010 behaviour understand

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#187]
I have few questions about introducing manylinux210 to cibuildwheel.

1. Why manylinux2010 build both manylinux1 and manylinux2010 wheels (Why to do this if something can be compiled to manylinux1 then is no ned for manylix2010 ??) 

2. What is some extensions need c++14 or c++17. The manylinux2010 container has proper compilers, but it may use some features not available for old images. (??)

**Comment by YannickJadoul** [comment]
@Czaki 

1. There's been a veeeeery long discussion in #155 and #135. Short answer: `manylinux1` and `manylinux2010` are standards on what versions of libraries can be used (`glibc`, etc); see [PEP 513](https://www.python.org/dev/peps/pep-0513/) and [PEP 571](https://www.python.org/dev/peps/pep-0571/), and sometimes a wheel compiled on the `manylinux2010` image is still `manylinux1`. We've discussed this at length, and so have the folks from manylinux and auditwheel, and the main conclusion was that it's fine to return multiple wheels.
2. I don't understand? `manylinux2010` has newer versions of compilers, so you should be able to use newer C++ standards. Apart from that, if you want to use even newer compiler versions that require a post-manylinux2010 standard library, the same principle probably goes as for `manylinux1`: https://github.com/pypa/manylinux/issues/118

**Comment by Czaki** [comment]
So current solution, if it is possible build manylinux1 and manylinux2010, and if some new things not supported by manylinux1 is needed then only manylinux2010 wheel is produced?

**Comment by YannickJadoul** [comment]
Well, just one wheel is built. And if that happens to be `manylinux1` compatible, `auditwheel` wil give you two copies, one tagged with `manylinux1` and the other with `manylinux2010`.

And every `manylinux1` wheel is also compatible with `manylinux2010`, so if you still need to be sure you have `manylinux1`, you can say `CIBW_MANYLINUX_IMAGE="manylinux1"`.

**Comment by Czaki** [comment]
Ok. Thanks. My question is connected with question "What I need to upload to pypi?". "If there is any advantage of upload both wheels to pypi?" 

Now I have bases to think about this.

**Comment by YannickJadoul** [comment]
That's still not completely clear to me. Do read the further discussions we had on keeping 1 or 2 wheels, and the link to the pypa/manylinux discussion in there, where I asked the same question and got an answer: https://github.com/pypa/manylinux/issues/179#issuecomment-520512039

**Comment by YannickJadoul** [comment]
Is that OK with you? Can we close this issue and get the issues counter one down again? :)
