### ISSUE TITLE
cibuildwheel: Unable to detect platform.

### ISSUE THREAD

**Issue by horta** [joerick/cibuildwheel#196]
I'm getting 

```
cibuildwheel: Unable to detect platform. cibuildwheel should run on your CI server, Travis CI, AppVeyor, and CircleCI are supported. You can run on your development machine using the --platform argument. Check --help output for more information.
```

on Travis-CI Windows because the latest cibuildwheel version (```0.12.0```) does not contain the line https://github.com/joerick/cibuildwheel/blob/0375e92110113689025a5f05376f77d220d8b5c9/cibuildwheel/__main__.py#L68

Is it possible to release a ```0.12.1``` version soon?

Thanks a lot for this tool. It had help many of my projects.

**Comment by YannickJadoul** [comment]
@horta Windows isn't yet supported on Travis CI in 0.12.0, I think: https://github.com/joerick/cibuildwheel/blob/aeeac6725a707ab7396fa3cb460cd143a0e42d6d/README.md

It will be, soon, when a new version, including support for Python 3.8, ... gets released!
Meanwhile, if you can't wait, you can `pip install git+https://github.com/joerick/cibuildwheel.git`. The `master` branch is rather stable, and I've not often known it to break.

**Comment by horta** [comment]
That is what I have been doing =) Thanks @YannickJadoul

**Comment by joerick** [comment]
v1.0.0 is now released :)
