### ISSUE TITLE
Add support for manylinux2014

### ISSUE THREAD

**Issue by mayeut** [joerick/cibuildwheel#216]
Add support for manylinux2014

c.f. https://github.com/pypa/manylinux/issues/338

manylinux2014 now also allows for different architecture than `x86_64`/`i686`
Images are also available for `aarch64`/`ppc64le`/`s390x`

**Comment by YannickJadoul** [comment]
>  Images are also available for `aarch64`/`ppc64le`/`s390x`

Seems Travis CI is/has been working on this: https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by joerick** [comment]
Implemented in #215, Released in v1.1.0
