### ISSUE TITLE
Wheels only get installed if CIBW_TEST_COMMAND is not empty

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#219]
We're only `pip install`ing the build wheels when `CIBW_TEST_COMMAND` is set.

If the build wheel is somehow not installable, such as in a weird case of a build of #185 (still debugging what's going on there), that results in the first test succeeding, but the second one (which does set `CIBW_TEST_COMMAND`) failing:

- https://circleci.com/gh/joerick/cibuildwheel/2307
- https://travis-ci.org/joerick/cibuildwheel/jobs/613504479#L963
- https://dev.azure.com/joerick0429/cibuildwheel/_build/results?buildId=468

Do we need to address this by always creating the virtualenv and installing the wheel? Or is this a weird corner case? (I mean: I'm assuming the wheel is correctly built, but it's weird that a later version than the macOS that is running is built. But this might be a PyPy issue, rather than `cibuilwheel`?)

I can easily enough make a PR to fix/change this, but I first wanted an opinion on whether to address it or not?

**Comment by joerick** [comment]
Yeah, this is a fair point. We could document it inside the CIBW_TEST_COMMAND option docs- perhaps an example that sets `CIBW_TEST_COMMAND: "echo Wheel installed"` and a reduced description of the above would do the trick.

**Comment by YannickJadoul** [comment]
Hmmm, interesting suggestion.
Setting up the `virtualenv` is one of the things that takes quite some time in builds, if I recall correctly? So just always installing the built wheel is a bit overkill?
