### ISSUE TITLE
macOS on AppVeyor

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#225]
Apparently macOS is now available on AppVeyor: https://www.appveyor.com/docs/macos-images-software/

If I'm not mistaken, this should be simple enough to add, by just correctly detecting the new CI platform in `__main__.py`, or not even?

**Comment by Czaki** [comment]
for 10.14 image most probably yes. For 10.15 it is connected with #194 
MacOS from version 10.15 drop support for 32 bits.

**Comment by mayeut** [comment]
It seems it's documented but not available yet on all accounts: https://ci.appveyor.com/project/mayeut/cibuildwheel/builds/29069646/job/2sfphi7kl59rvddg/events
I've done attempts with `macos`, `macos-mojave` and `macOS`. Each time, I get `Build worker image not found: ...`

Then, Found the blog post: https://www.appveyor.com/blog/2019/11/20/build-macos-projects-with-appveyor/
> macOS builds are available to everyone by request - send us an email.

**Comment by YannickJadoul** [comment]
>> macOS builds are available to everyone by request - send us an email.

Aaaah, right! That was also in the email I got, but seems I didn't read that last line :-)

Anyway, let's relay this to @joerick then, as he probably needs to send that email (or decide to wait until it's fully public before adding it to `cibuildwheel`).

**Comment by mayeut** [comment]
Now supported, tests/docs added in #230
