### ISSUE TITLE
Output information on total time to build wheel

### ISSUE THREAD

**Issue by astrofrog** [joerick/cibuildwheel#227]
In build logs such as https://dev.azure.com/astropy-project/reproject/_build/results?buildId=185, it's difficult to see how long each build took since there are multiple builds done at the same time. It would be nice to have information about when a build is started, then when it ends, and when it ends it could output total time information (this would be the total time for set-up, building, and testing). So I'm thinking something like:

```
--------- Start build with platform manylinux1_i386 at 13:22:10 ---------
<set up python, install build deps, build, test>
------ End build with platform manylinux1_i386 at 13:32:10 (600s) ------
```

**Comment by henryiii** [comment]
This was added with folding in 1.7.0 and #458.

<img width="529" alt="Screen Shot 2021-01-31 at 11 44 45 PM" src="https://user-images.githubusercontent.com/4616906/106416026-80f0e700-641e-11eb-9f14-5ea9b10cade8.png">
