### ISSUE TITLE
widows build on github actions

### ISSUE THREAD

**Issue by samuelcolvin** [joerick/cibuildwheel#244]
First the good news: cibuildwheel is building wheels correctly for linux and macos on github actions. Thank you.

The only problem is windows builds which are failing with:
```
+ python C:\cibw\get-pip.py
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-19.3.1
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\Scripts\cibuildwheel.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\site-packages\cibuildwheel\__main__.py", line 180, in main
    cibuildwheel.windows.build(**build_options)
  File "c:\hostedtoolcache\windows\python\3.7.5\x64\lib\site-packages\cibuildwheel\windows.py", line 128, in build
    assert os.path.exists(os.path.join(config_python_path, 'Scripts', 'pip.exe'))
AssertionError
```

cibuildwheel setup details:
```
cibuildwheel version 1.1.0

Build options:
  platform: 'windows'
  before_build: '{project}/.github/workflows/install-rust.sh'
  build_selector: BuildSelector('cp37-*' - '')
  build_verbosity: 0
  environment: ParsedEnvironment(['PATH="$HOME/.cargo/bin:$PATH"'])
  output_dir: 'dist'
  project_dir: '.'
  repair_command: ''
  test_command: 'python -c "import rtoml"'
  test_extras: ''
  test_requires: []
```

You can see the full build [here](https://github.com/samuelcolvin/rtoml/pull/4/checks?check_run_id=383939310). The pull request to add macos and windows builds is https://github.com/samuelcolvin/rtoml/pull/4. 

I'm aware that `CIBW_BEFORE_BUILD` is probably going to fail as soon as I get this problem fixed, but I thought it worth reporting this first.

Is there any chance of a quick fix or workaround for this? If not I'll skip windows binaries for the time being.

**Comment by samuelcolvin** [comment]
I'm not clear whether this will be fixed by #194, I don't think it would, but I could be wrong.

**Comment by YannickJadoul** [comment]
@samuelcolvin Officially, we're indeed still waiting for #194 to be finished/merged before GitHub Actions are supported.
To solve this error, it would be good to know where `pip` actually gets installed. If you want to play around, I'd suggest to add some `-v` or `-vv` verbosity flags to the relevant line in `windows.py`: https://github.com/joerick/cibuildwheel/blob/d17517902e1f2fa6059a4569197eac41be04619a/cibuildwheel/windows.py#L140

Otherwise, could you just use `AppVeyor` to build Windows wheels, until we can provide the GitHub Actions support?

**Comment by samuelcolvin** [comment]
ok
