### ISSUE TITLE
Setuptools changed behaviour of pip wheel 

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#247]
I observe that updates of `setuptools` (I have hope that I identify correct) changed behavior of `pip wheel ..` command. It creates sub environment and install some packages from scratch. In this moment I'm not exactly sure what this change globally (for me it breaks using pre-release wheel package). 

This is also argument for #239 suggested pininng of packages.

 In this moment I'm not sure how big impact of this change is on `cibuildwheel`. It should be at least additional notes in documentation.

**Comment by YannickJadoul** [comment]
Do you have a reference to what changed?

Sounds quite annoying, indeed. It feels like our tests should have detected this? :-/

**Comment by Czaki** [comment]
Not yet. I found that when I restart build it behave different. 
In my case it is connected with #156. I observe that it stop setting proper wheel name. I found that it install wheel from pypi instead of use local one.

**Comment by joerick** [comment]
I agree, this kind of thing suggests to me that deterministic builds by default would be a good idea.

Tests are still passing here, so maybe it was only a temporary bug that got fixed.

**Comment by Czaki** [comment]
@joerick This is connected with PEP 517. Test build does not use PEP 517 and 518 so are not affected.

**Comment by joerick** [comment]
Hmm, maybe we should include a test that uses pyproject.toml so we have visibility on this...
