### ISSUE TITLE
1.2.0 release

### ISSUE THREAD

**Issue by joerick** [joerick/cibuildwheel#267]
Hi @YannickJadoul @mayeut,

Just wanted to ask a quick question on the next release - I'm thinking that we've made a lot of progress with cibuildwheel in the last couple months: [PRs merged since last release](https://github.com/joerick/cibuildwheel/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A%3E2019-12-07)

So I'm thinking it could be time for the 1.2.0 release. At the same time there are some big PRs that seem quite close to release (Pypy #143, Github actions #194, deterministic builds #256) - would you guys like those in 1.2.0 too? There's no need to rush, but if you'd like to get them in, please just shout and I'll hold off on another release until then.

Also logging things I need to remember for the 1.2.0 release:

- [x] update the examples in `/examples` to use `python3` rather than `python`
- [x] update joerick/cibuildwheel-auto-pypi to use `python3`

**Comment by YannickJadoul** [comment]
Yeah, I still need to have a look at the PyPy PR, but if you want, I think we could still get it in. We're closer to finishing it than I thought.

**Comment by joerick** [comment]
Cool, I'll hold off until that's ready.

**Comment by YannickJadoul** [comment]
I'll make sure I'll make some time for this, next week, then!

**Comment by Czaki** [comment]
See #272 It may block release.

**Comment by joerick** [comment]
Do the virtualenv 20 problems block release, or should we do one with virtualenv pinned to <20? I'd like to get a release out before #256 ideally.

**Comment by Czaki** [comment]
Problem is deeper. I create #282  which test if virtualenv is properly used. And it fail with pypy on windows even if virtualenv is forced to be bellow 20 (see #283). 

If you want to do release fast I suggest to disable pypy on windows...

**Comment by Czaki** [comment]
@joerick I created PR #282 and #283 with different ways to workaround pypy virtualenv problem. Choose which one is better. 

Then #256 can be easy merged.

**Comment by YannickJadoul** [comment]
@joerick The two original virtualenv issues have been solved and worked around.

I'll have a look at the two PRs soon. Thanks for taking care of this, @Czaki!

**Comment by joerick** [comment]
Released! 4628c1334e3350630710bff2a148ab1e18ff2464

**Comment by YannickJadoul** [comment]
Pffffff, I turn my back for a week and I've missed a dozen PRs and a release :-D

Nice work, @Czaki and @joerick ;-)
