### ISSUE TITLE
Add support for non-x86 architectures with manylinux2014

### ISSUE THREAD

**Issue by mtreinish** [joerick/cibuildwheel#269]
With manylinux2014 there is support for publishing wheels on non-x86 architectures. There are docker images available for all the supported architectures: https://github.com/pypa/manylinux#manylinux2014 and travis supports running CI on these architectures too: https://docs.travis-ci.com/user/multi-cpu-architectures/. Having options available to specify a non-x86 builds and docker images would be great for projects that want to support users on other architectures.

**Comment by joerick** [comment]
Totally agree this would be great! By the way, nothing in the current manylinux build is specific to x86, so I tried one on the manylinux2014-aarch64 (arm64) build. It [ran, but didn't get very far](https://travis-ci.org/joerick/cibuildwheel-autopypi-example/builds/648057310),  I guess the paths to each Python are different on those images.

PRs welcome! If anyone wants to take a crack at this, let's chat API and build identifiers before you start :)

**Comment by mtreinish** [comment]
I think I might have time to take a crack at this over the next week or so. For the new identifiers I was thinking of just following the same pattern: `cp*--manylinux_aarch64`, `cp*-manylinux_ppc64le` and `cp*--manylinux_s390x`. Looking at the [manylinux2014 spec](https://www.python.org/dev/peps/pep-0599/#the-manylinux2014-policy) there is also support for `armv7l` and  `ppc64` (big endian) but without a docker image or host env in CI for either I'm not sure we'll be able to support those.

I was thinking of also adding options for the docker image: `CIBW_MANYLINUX_AARCH64_IMAGE`, `CIBW_MANYLINUX_PPC64LE_IMAGE`, and `CIBW_MANYLINUX_S390X_IMAGE`.

**Comment by YannickJadoul** [comment]
@mtreinish That would be amazing. I agree with those names; they're the same as in the manylinux standard, so no need to make up something else if there's not specific reason :-)

PyPy also supports some of these architectures, btw: https://www.pypy.org/download.html#python2-7-compatible-pypy-7-3-0. Though I don't think they have manylinux images :-/
