### ISSUE TITLE
Avoid Python2 Deprecation error by just building python 3 targets?

### ISSUE THREAD

**Issue by stuaxo** [joerick/cibuildwheel#271]
Hi,
  I'm experimenting with cibuildwheel on travis.

My build only has python3 targets but I'm hitting and error about python2 being deprecated.

Any idea if I can build the wheel for python3 target(s) ?

https://travis-ci.org/stuaxo/pycairo/jobs/649985094#L1281

Cheers
Stuart

**Comment by joerick** [comment]
Sure, check the docs for CIBW_BUILD and CIBW_SKIP: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

Probably you'll just want to set `CIBW_SKIP: cp27-*`.

**Comment by stuaxo** [comment]
For anyone else that ends up here, don't accidentally copy the "." after the example env var, just copy:

`CIBW_SKIP: cp27-*`

**Comment by YannickJadoul** [comment]
Yes, it's not there in the docs: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

**Comment by stuaxo** [comment]
User error on my part, as I'm doing this in gaps at work as I wait for something else to build.
