### ISSUE TITLE
Cannot find cannot find -llapack and -lblas whenc creaing wheel for manylinux2010_i686 in python 3.7

### ISSUE THREAD

**Issue by ysig** [joerick/cibuildwheel#275]
Hi,

I get the following error only when [creating a wheel](https://travis-ci.org/ysig/GraKeL/jobs/653413885) for manylinux2010_i686 in python 3.7 (it works for all other versions!!)

>   /opt/rh/devtoolset-7/root/usr/libexec/gcc/i686-redhat-linux/7/ld: cannot find -llapack
>   /opt/rh/devtoolset-7/root/usr/libexec/gcc/i686-redhat-linux/7/ld: cannot find -lblas
>   collect2: error: ld returned 1 exit status
>   error: command 'gcc' failed with exit status 1

Thanks

**Comment by YannickJadoul** [comment]
Hi @ysig. I don't immediately see what's going on there, but have you tried running the docker images manually and checking the differences between `x86_64` and `i686`, or Python 3.6 and 3.7?

While I'd love to help, so far, I'm not sure/convinced this issue is linked to cibuildwheel. It might also just be something weird about the manylinux images and their toolchains that you're using...

**Comment by ysig** [comment]
No I have not, but it's strange as it used to work on previous versions and
works on OSX too.

Στις Σάβ, 22 Φεβ 2020 στις 2:13 μ.μ., ο/η Yannick Jadoul <
notifications@github.com> έγραψε:

**Comment by YannickJadoul** [comment]
> No I have not, but it's strange as it used to work on previous versions and works on OSX too.

I agree, but I don't really know where to start debugging, other than trying this locally and manually building wheels in the docker images.
The few clues I have are:
- `manylinux2010_i686` uses an older version of GCC: pypa/manylinux#409
- Python 3.7 is used as the main Python version to install `auditwheel` etc
- macOS doesn't use these manylinux docker images

**Comment by joerick** [comment]
Hey @ysig. I agree that this is very strange! Have you tried `yum install`ing those deps to ensure they're available system-wide during the build? 

However, I agree with @YannickJadoul that this is unlikely to be a cibuildwheel problem - it's more likely to be something in your config, setuptools, or manylinux2010. 

Confirming that those dependencies are installed and on the linker path would be your first step, I suppose.
