### ISSUE TITLE
Bump MacOS build image on Azure Pipelines

### ISSUE THREAD

**Issue by paulmelnikow** [joerick/cibuildwheel#276]
Azure Pipelines is removing the `macOS-10.13` build image on 3/23. There's [more information in this blog post](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/)

I came across this by running cibuildwheel using the Azure instructions here. I'm seeing this message:

> This pipeline uses a Microsoft-hosted agent image that will be removed on March 23, 2020 (MacOS-10.13). You must make changes to your pipeline before that date, or else your pipeline will fail. Learn more (https://aka.ms/removing-older-images-hosted-pools)

I upgraded to the 10.15 images and they seem to be working fine: https://github.com/tinyobjloader/tinyobjloader/pull/260

**Comment by YannickJadoul** [comment]
Thanks for taking the time to make that PR, after bumping into those docs! :-)
