### ISSUE TITLE
appveyor.yml does not parse

### ISSUE THREAD

**Issue by dr-leo** [joerick/cibuildwheel#28]
Hi,

thanks for this very useful project.

I am trying to use CIBuildWheel to build wheels for PyHyphen, a hyphenation lib for Python. Se https://bitbucket.org/fhaxbox66/pyhyphen.

It has a C extension. I want to use cibuildwheel to generate wheels for all common Windows and Python versions. I no nothing about CI configuration and find the appveyor docs too concise. So I naively copied the demo appveyor.yml file from the cibuild docs. Here is the build error:
  

Error parsing appveyor.yml: (Line: 4, Col: 5, Idx: 106) - (Line: 4, Col: 5, Idx: 106): While parsing a block mapping, did not find expected key

Any hint would be much appreciated.

Leo

**Comment by mayeut** [comment]
Seems indentation is not right in your file.

Have a look at this file https://raw.githubusercontent.com/joerick/cibuildwheel-autopypi-example/4656c3b0de4ee1f776252a62c9c1cd8bbd8c5dec/appveyor.yml

**Comment by dr-leo** [comment]
Thanks. You were right. Now it parses the file properly.

**Comment by joerick** [comment]
I've updated the indentation in the readme so hopefully this won't happen to anyone else! 😃

**Comment by dr-leo** [comment]
Hi,

just to let you know that I managed to configure it as I wanted to. PyHyphen 3.0.1 Comes with wheels from appveyor thanks to you guys. It's an incredibly useful tool. Luckily, appveyor Supports bitbucket repos. Travis doesn't so we could not build for MacOS. OK for us.  

I tried running Tests with python stdlib's unittest command but it failed for an unknown reason. Using pytest works just fine. If there's a common Problem here, you may want to flag it somewhere. 

Feel free to add PyHyphen to the list of demo repos. I lack the time to do a PR for this.

Cheers, Leo
