### ISSUE TITLE
Autoformatter usage

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#280]
There were discussion about keeping code formatted to satisfy pep8. Maybe better solution is to use autoformater that will simplify maintenance. In my other projects I use black (https://github.com/psf/black) and I like this solution. After finish changes in code fix formatting mistakes is one command.

**Comment by YannickJadoul** [comment]
> There were discussion about keeping code formatted to satisfy pep8.

Not just a discussion. It is being checked by `flake8` as a CI job: #212.
On the matter of using black: is that something we need to decide/provide in the project? Isn't that just an individual tooling choice?

**Comment by Czaki** [comment]
Black has more rules than pep8. So pep8 compatibile code could be still reformatted by black. 

So still if I would like use black on my PR then it ill change also other part of code. 

There is also opened bug that in one case flake8 will fail on black output (additional coma).

**Comment by YannickJadoul** [comment]
I see. So for higher consistency, adding a configuration for black would be good?

That being said, I don't feel like the code is currently so messy, and I (personally) like a little bit of margin around these rules. But I guess this is a matter for @joerick, then :-)

**Comment by Czaki** [comment]
You can see difference here: 
https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc

I also would like to propose some code refactor, but doing this will break opened PR especially #256.

**Comment by YannickJadoul** [comment]
> You can see difference here:
> [Czaki@11bc1ca](https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc)

Thanks for that.

Now I'm less convinced, though. I really don't get this line length obsession of formatters/code conventions. In what world is [that](https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc#diff-22075e43d4ff5efd0d10f3dcffdb93aaR40-R117) more readable than [this](https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc#diff-22075e43d4ff5efd0d10f3dcffdb93aaL40-L65)?  Or [that](https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc#diff-22075e43d4ff5efd0d10f3dcffdb93aaR292-R331) vs. [this](https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc#diff-22075e43d4ff5efd0d10f3dcffdb93aaL207-L215)?

Also, I've noticed @joerick to replace single quotes by double quotes, before, in PRs, and I've been trying to be consistent with that as well. So does black then change them all back to double quotes?

> I also would like to propose some code refactor, but doing this will break opened PR especially #256.

I would argue #256 is definitely too delicate (already the rebase/merge with the PyPy PR is going to be quite horrible, I think). So it would definitely be good to have a release and have less big PRs open; but meanwhile, you could already open an issue to discuss what you want to do, ofc.

**Comment by Czaki** [comment]
> Now I'm less convinced, though. I really don't get this line length obsession of formatters/code conventions. In what world is that more readable than this? Or that vs. this?

line length can be controlled:
https://github.com/Czaki/cibuildwheel/commit/daf4d3ca26496b8dfc6a74533bf7e82810f3588c

> Also, I've noticed @joerick replacing single quotes by double quotes, before, in PRs, and I've been 
trying to be consistent with that as well. So does black then change them all back to double quotes?

Yes. Persons from psf thinks that double quotes are better

**Comment by joerick** [comment]
Style is one of those things that can can generate unnecessary amounts of discussion. So I hope you'll forgive me curtailing that by making an autocratic decision!

I've decided `black` is not a good fit for this project.

See things like https://github.com/Czaki/cibuildwheel/commit/11bc1ca5abf577abb2819e7df3c6ba88c33256bc#diff-22075e43d4ff5efd0d10f3dcffdb93aaL207-L212

The line breaks are purposeful and have meaning. Tools shouldn't be stripping away human meaning from code.

**Comment by henryiii** [comment]
I am strongly in favor of Black, by the way. Going back over my code just to style it properly is really irritating, and I find Black _much_ easier to read that custom formatting (especially when you work on dozens of projects). There are _rare_ cases where custom formatting may be needed (I've so far always been able to work around them by refactoring my code and have always been happier with the result - something hard to auto format is also hard to read), but if you have that, just add `# fmt: on` and `#fmt: off` around the special block. Then it tells the reader that this is special too.

Remember, Python only sees code, not format. So trying to infuse whitespace with special meaning distracts from what you are actually doing. That's what comments are for.

**Comment by henryiii** [comment]
Also the lines are soooo long! I have to readjust everything just so see what is going on; I can't split my screen as I would normally do.

**Comment by henryiii** [comment]
Also, with https://pre-commit.ci, you don't even need to have contributors use black or even pre-commit; the bot corrects pull requests for you.

**Comment by YannickJadoul** [comment]
I'm still really not a fan of Black. It keeps on fighting my code that I was happy about... :-/

> Remember, Python only sees code, not format. So trying to infuse whitespace with special meaning distracts from what you are actually doing. That's what comments are for.

I think (in general), I just use whitespace etc. to group things, without it being a "special meaning" (I agree that should be explicit; but comments also distract), in ways like e.g. described in https://www.fluentcpp.com/2020/01/14/the-shapes-of-code/. Python also doesn't see empty lines, but they are still plain necessary in code, no?

I see the point that having some kind of formatter might be nice. But then again, I don't think review has ever been that harsh over formatting?
