### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by louisabraham** [joerick/cibuildwheel#284]
I think the docker image calls python2.

https://travis-ci.org/louisabraham/pydivsufsort/jobs/657405475

**Comment by joerick** [comment]
Hi! cibuildwheel is trying to build your package for Python 2. The missing import is coming from your package's `setup.py`. If you want to skip building Python 2 wheels, set `CIBW_SKIP=cp27-*`.

**Comment by louisabraham** [comment]
Thanks!
