### ISSUE TITLE
CIBW_BUILD_REQUIRES

### ISSUE THREAD

**Issue by louisabraham** [joerick/cibuildwheel#288]
It would be great e.g. to install Cython.

**Comment by louisabraham** [comment]
The problem is that when one cannot find the version of python that will be used to build the wheels, it is not possible to install modules outside of setup.py. This is required when setup.py uses those modules, like Cython or numpy.

**Comment by louisabraham** [comment]
I think that `pip` works everywhere since it's used to install wheel by cibuildwheel. It would be nice to mention it somewhere.

**Comment by joerick** [comment]
The docs for CIBW_BEFORE_BUILD say:

> The active Python binary can be accessed using python, and pip with pip; cibuildwheel makes sure the right version of Python and pip will be executed.

Is that what you mean?

**Comment by joerick** [comment]
`CIBW_BEFORE_BUILD=pip install <your-requirements>` should work for your use case.

**Comment by louisabraham** [comment]
Oh, I'm sorry, I read the doc too fast and ended up looking at the code 🤦‍♂
