### ISSUE TITLE
Universal wheel is created whereas version-specific wheels should be

### ISSUE THREAD

**Issue by dr-leo** [joerick/cibuildwheel#29]
Hi,

trying to build PyHyphen which has a C extension, the first build passes, but the second one fails due to shutil error. See the log below. 

If PyHyphen's setup.cfg should be changed to explicitly guide the wheel build process, pls let me know. This should then be documented.

Leo

1
Build started
2
hg clone -r 1312cc107dbc6c378bac95936c934a60f4299c40 https://bitbucket.org/fhaxbox66/pyhyphen C:\projects\pyhyphen
3
adding changesets
4
adding manifests
5
adding file changes
6
added 76 changesets with 225 changes to 55 files
7
updating to branch default
8
42 files updated, 0 files merged, 0 files removed, 0 files unresolved
9
pip install cibuildwheel==0.4.1
10
Collecting cibuildwheel==0.4.1
11
  Downloading cibuildwheel-0.4.1.tar.gz
12
Installing collected packages: cibuildwheel
13
  Running setup.py install for cibuildwheel: started
14
    Running setup.py install for cibuildwheel: finished with status 'done'
15
Successfully installed cibuildwheel-0.4.1
16
cibuildwheel --output-dir wheelhouse
17
18
     _ _       _ _   _       _           _
19
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
20|
 _| | . | | | | | . | | | |   | -_| -_| |
21
|___|_|___|___|_|_|___|_____|_|_|___|___|_|
22
23
cibuildwheel version 0.4.1
24
25
Build options:
26
  platform: 'windows'
27
  output_dir: 'wheelhouse'
28
  package_name: 'PyHyphen'
29
  before_build: None
30
  skip: BuildSkipper('')
31
  project_dir: '.'
32
  test_requires: []
33
  test_command: None
34
35
Here we go!
36
37
+ python --version
38
Using default MSVC build environment for 32 bit architecture
39
Executing: python --version
40
Python 2.7.13
41
+ python -c "import struct; print(struct.calcsize('P') * 8)"
42
Using default MSVC build environment for 32 bit architecture
43
Executing: python -c "import struct; print(struct.calcsize('P') * 8)"
44
32
45
+ pip install --disable-pip-version-check --user --upgrade pip
46
Using default MSVC build environment for 32 bit architecture
47
Executing: pip install --disable-pip-version-check --user --upgrade pip
48
Requirement already up-to-date: pip in c:\python27\lib\site-packages
49
+ pip install wheel
50
Using default MSVC build environment for 32 bit architecture
51
Executing: pip install wheel
52
Collecting wheel
53
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
54
Installing collected packages: wheel
55
Successfully installed wheel-0.29.0
56
+ pip wheel . -w c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel --no-deps
57
Using default MSVC build environment for 32 bit architecture
58
Executing: pip wheel . -w c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel --no-deps
59
Processing c:\projects\pyhyphen
60
Building wheels for collected packages: PyHyphen
61
  Running setup.py bdist_wheel for PyHyphen: started
62
  Running setup.py bdist_wheel for PyHyphen: finished with status 'done'
63
  Stored in directory: c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel
64
Successfully built PyHyphen
65
+ pip install c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\PyHyphen-3.0.0-py2-none-any.whl
66
Using default MSVC build environment for 32 bit architecture
67
Executing: pip install c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\PyHyphen-3.0.0-py2-none-any.whl
68
Processing c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\pyhyphen-3.0.0-py2-none-any.whl
69
Collecting appdirs (from PyHyphen==3.0.0)
70
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
71
Collecting six (from PyHyphen==3.0.0)
72
  Downloading six-1.10.0-py2.py3-none-any.whl
73
Installing collected packages: appdirs, six, PyHyphen
74
Successfully installed PyHyphen-3.0.0 appdirs-1.4.3 six-1.10.0
75
+ python --version
76
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
77
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
78
Targeting Windows Server 2008 x64 RELEASE
79
80
Executing: python --version
81
Python 2.7.13
82
+ python -c "import struct; print(struct.calcsize('P') * 8)"
83
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
84
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
85
Targeting Windows Server 2008 x64 RELEASE
86
87
Executing: python -c "import struct; print(struct.calcsize('P') * 8)"
88
64
89
+ pip install --disable-pip-version-check --user --upgrade pip
90
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
91
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
92
Targeting Windows Server 2008 x64 RELEASE
93
94
Executing: pip install --disable-pip-version-check --user --upgrade pip
95
Requirement already up-to-date: pip in c:\python27-x64\lib\site-packages
96
+ pip install wheel
97
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
98
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
99
Targeting Windows Server 2008 x64 RELEASE
100
101
Executing: pip install wheel
102
Collecting wheel
103
  Using cached wheel-0.29.0-py2.py3-none-any.whl
104
Installing collected packages: wheel
105
Successfully installed wheel-0.29.0
106
+ pip wheel . -w c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel --no-deps
107
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
108
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
109
Targeting Windows Server 2008 x64 RELEASE
110
111
Executing: pip wheel . -w c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel --no-deps
112
Processing c:\projects\pyhyphen
113
Building wheels for collected packages: PyHyphen
114
  Running setup.py bdist_wheel for PyHyphen: started
115
  Running setup.py bdist_wheel for PyHyphen: finished with status 'done'
116
  Stored in directory: c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel
117
Successfully built PyHyphen
118
+ pip install c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\PyHyphen-3.0.0-py2-none-any.whl
119
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
120
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
121
Targeting Windows Server 2008 x64 RELEASE
122
123
Executing: pip install c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\PyHyphen-3.0.0-py2-none-any.whl
124
Processing c:\users\appveyor\appdata\local\temp\1\cibuildwheel4izxch\built_wheel\pyhyphen-3.0.0-py2-none-any.whl
125
Collecting six (from PyHyphen==3.0.0)
126
  Using cached six-1.10.0-py2.py3-none-any.whl
127
Collecting appdirs (from PyHyphen==3.0.0)
128
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
129
Installing collected packages: six, appdirs, PyHyphen
130
Successfully installed PyHyphen-3.0.0 appdirs-1.4.3 six-1.10.0
131
Traceback (most recent call last):
132
  File "C:\Python27\Scripts\cibuildwheel-script.py", line 11, in <module>
133
    load_entry_point('cibuildwheel==0.4.1', 'console_scripts', 'cibuildwheel')()
134
  File "c:\python27\lib\site-packages\cibuildwheel\__main__.py", line 116, in main
135
    cibuildwheel.windows.build(**build_options)
136
  File "c:\python27\lib\site-packages\cibuildwheel\windows.py", line 101, in build
137
    shutil.move(built_wheel, output_dir)
138
  File "c:\python27\lib\shutil.py", line 292, in move
139
    raise Error, "Destination path '%s' already exists" % real_dst
140
shutil.Error: Destination path 'wheelhouse\PyHyphen-3.0.0-py2-none-any.whl' already exists
141
Command exited with code 1

**Comment by dr-leo** [comment]
This is actually no bug. The behavior was due to the fact that PyHyphen compiled as pure Python under certain circumstances. I've fixed this and am excited about the first wheels I've successfully built with CIBuildWheel.

Thanks again for an excellent project.

Leo

**Comment by joerick** [comment]
\😁/ Glad you got it sorted @dr-leo !
