### ISSUE TITLE
CIBuildwheel 1.3.0 failing for Linux

### ISSUE THREAD

**Issue by hameerabbasi** [joerick/cibuildwheel#299]
Here's the log:
https://dev.azure.com/Quansight-Labs/uarray/_build/results?buildId=585&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03

Relevant part, for convenience:
```
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 8, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main_repair.py", line 49, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/repair.py", line 14, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/wheeltools.py", line 17, in <module>
    from wheel.wheelfile import WHEEL_INFO_RE  # type: ignore
ModuleNotFoundError: No module named 'wheel.wheelfile'
```

**Comment by MuellerSeb** [comment]
Same on travis!

**Comment by MuellerSeb** [comment]
Auditwheel updated it's dependecy to `wheel==0.34`:
https://github.com/pypa/auditwheel/blob/ea1e0f0ea3e0336e8cbe235b4f022ac8aee36c5f/auditwheel/wheeltools.py#L17

Manylinux was updated to use auditwheel 3.1.0:
https://github.com/pypa/manylinux/commit/f878e29fe8b81a2921807cb9e299c941c1ed37ea

So you have to ensure that `wheel==0.34` is installed.

**Comment by MuellerSeb** [comment]
An issue was opened at maylinux addressing this:
https://github.com/pypa/manylinux/issues/512

**Comment by hameerabbasi** [comment]
Thanks for the digging, @MuellerSeb!

**Comment by MuellerSeb** [comment]
So, this issue needs to be solved by manylinux.
Cheers

**Comment by MuellerSeb** [comment]
Should be done with: https://github.com/pypa/manylinux/commit/a2d83911f4bc8b35dbf34a90ce552c71daee0ef1

**Comment by hameerabbasi** [comment]
Confirmed: https://dev.azure.com/Quansight-Labs/uarray/_build/results?buildId=587&view=logs&j=50a69d0a-7972-5459-cdae-135ee6ebe312
