### ISSUE TITLE
Implement CIBW_SKIP

### ISSUE THREAD

**Issue by joerick** [joerick/cibuildwheel#3]
The API for this feature is designed (as in README), but it needs implementation.

If this feature would be useful to you, comment below and I might prioritise it over other work.

**Comment by zfrenchee** [comment]
@joerick I'm voting for this ;)

**Comment by joerick** [comment]
You might give the branch `skip` a try!

    pip install git+https://github.com/joerick/cibuildwheel@3f6a943b6d6a1e47a3c4f7e6930dadd171374a22

I think the option in your case would be `CIBW_SKIP=cp26-*`
