### ISSUE TITLE
Things to do once Python 3.5 host support is dropped

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#316]
List of things we could potentially do once we require a minimal Python version of 3.6 to execute `cibuildwheel`.

- f-strings!
- `pathlib` (`pathlib` already exists in 3.5, but the [path protocol](https://www.python.org/dev/peps/pep-0519/#provide-os-fspathb) doesn't, so lots of conversions to `str` are required).

If we have typing:
- Variable annotation syntax (local variables and `NamedTuple`)

**Comment by Czaki** [comment]
Remove `object` inheritance eg in `DependencyConstraints` (it should be done earlier)

What do you think about work with async (or threading) for speedup work (start installing next python before previous build wheel is finished)?

**Comment by YannickJadoul** [comment]
> Remove `object` inheritance eg in `DependencyConstraints` (it should be done earlier)

That's Python 2 vs. 3? I coul quickly commit that to `master` without PR, actually, if you want?

> What do you think about work with async (or threading) for speedup work (start installing next python before previous build wheel is finished)?

Not sure. I still feel that keeping things as slmple as possible is what we should aim for with `cibuildwheel`. I personally would rather have this tool work twice as slow but consistently, than have random failures because the installation accidentally added something the wheel did not expect?

**Comment by Czaki** [comment]
There are special options to be sure that some tasks not start before the one its depend on it finish. 
But I'm not sure if speed-up if worth of higher complexity.  

> That's Python 2 vs. 3? I coul quickly commit that to `master` without PR, actually, if you want?

This is simple code cleaning from unnecessary parts. It should be done in some moment.

**Comment by YannickJadoul** [comment]
> Remove `object` inheritance eg in `DependencyConstraints` (it should be done earlier)

@Czaki: not exactly the largest commit ever, but... b8dbedcdbed30d5f11dcbc9dcbc68a73040900ab
