### ISSUE TITLE
macOS target version and C++17

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#325]
Here we go again. Another subtlety/weirdness on macOS target versions and modern C++. Mind helping me to clear this one out, @Czaki?

So, full story:
- I recently [updated the pybind11 dependency of my project to a new version](https://github.com/YannickJadoul/Parselmouth/commit/70c83bb0ff2f577010a804136c66ae0ff02ed09e), which allows to opt out of C++17's ["aligned new"](https://en.cppreference.com/w/cpp/memory/new/operator_new) and ["sized deallocation"](https://en.cppreference.com/w/cpp/memory/new/operator_delete).
- I started playing around with `MACOSX_DEPLOYMENT_TARGET`, seeing if I could lower it from 10.14 (which was necessary before because of the size deallocation) to 10.13, and [found I could now set it to 10.9](https://github.com/YannickJadoul/Parselmouth/commit/476e7483a1db59ccbb254f129d41711f9d114eba), even though [the docs say C++17 requires >=10.13](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/) (while before ... I don't know, I needed 10.13 or 10.14.
- Fine, OK, I reckoned that maybe I'm still using a new compiler and maybe I don't really use any C++17-standard-library features, but just some STL and new compiler features. Just to be sure, I decided to test out on an old, pre-10.13 macOS version. Travis CI offers 10.10 as oldest version (first released in 2014, end of life in 2017; so this should be old enough to be pre-C++17 compilers? It's the closest I can easily get to 10.9 anyway, it seems, and should be way older than the 10.13/10.14 from the docs).
- I [made a repository today](https://github.com/YannickJadoul/Parselmouth-OSX-10.9), trying out the installation of an old and a new version, and, [it seems to work indeed](https://travis-ci.org/github/YannickJadoul/Parselmouth-OSX-10.9/jobs/679119747#L259) (hurray, good news!). The old version on my `stable` branch (from before the pybind11 update, that `wheel` labels `praat_parselmouth-0.3.3-cp37-cp37m-macosx_10_13_intel.whl`) doesn't install (of course, because the filename doesn't match the platform), does install when your rename it to `10_9_intel.whl` (also: of course, because you're lying to Python by changing the filename), but also [works](https://travis-ci.org/github/YannickJadoul/Parselmouth-OSX-10.9/jobs/679119747#L246)!?

So:
1. We should update our docs, right? Apparently it depends on the kinds of C++17 features you use, and if it's only compiler/STL features, you might be OK to target lower macOS versions? Or is my analysis wrong?
2. What the hell's going on with the supposedly incompatible wheel? Why does it work, even if `wheel` detects it's built against a newer macOS (version and labels it 10.13+)??

EDIT:
The `stable` branch is still using `cibuildwheel` 1.1.0 to build wheels, I believe. But that shouldn't matter, should it? The latest `wheel` normally still gets installed, and that's where @Czaki added the target version detection, if I remember correctly?

**Comment by Czaki** [comment]
It is realy hard to find full information for macos. Even to check clang version but looking on this page http://clang.llvm.org/cxx_status.html and this https://gist.github.com/yamaya/2924292 suggest that Xcode 6.4 offer partial support of c++17 (named c++1z). 

I check so file by `otool` and it show 10.13. I do not have any Idea why it work. Maybe this code does not use API newer than 10.10? 

> We should update our docs, right? Apparently it depends on the kinds of C++17 features you use, and if it's only compiler/STL features, you might be OK to target lower macOS versions? Or is my analysis wrong?

I think yes. But But (even in my native language) I do not have any idea how to write it properly to not get questions "Why my compilation fails?".

**Comment by YannickJadoul** [comment]
Thanks so much for quickly looking into this! :-)

> It is realy hard to find full information for macos. Even to check clang version but looking on this page http://clang.llvm.org/cxx_status.html and this https://gist.github.com/yamaya/2924292 suggest that Xcode 6.4 offer partial support of c++17 (named c++1z).

So, do you think I can try in another way? Maybe a macOS without Xcode installed?

> I check so file by `otool` and it show 10.13. I do not have any Idea why it work. Maybe this code does not use API newer than 10.10?

But but but ... compilation fails if I set `MACOSX_DEPLOYMENT_TARGET` lower, I think. Let me check again :-(

> I think yes. But But (even in my native language) I do not have any idea how to write it properly to not get questions "Why my compilation fails?".

Good point. I will try to carefully formulate something, if I find out what it is.

**Comment by Czaki** [comment]
> But but but ... compilation fails if I set `MACOSX_DEPLOYMENT_TARGET` lower, I think. Let me check again :-(

Check what happen If you use `c++1z` instead of `c++17`

**Comment by YannickJadoul** [comment]
> Check what happen If you use `c++1z` instead of `c++17`

How do you mean? `c++1z` was just the mode in older compilers before C++17 was released/ready, no? I don't think it exists on new OSes.

**Comment by Czaki** [comment]
On my laptop `c++1z` works (macos 10.14). And older xcode support `c++1z` and dose not support `c++17`. So maybe, if `c++17` compilation fails then `c++1z` will pass?

**Comment by YannickJadoul** [comment]
Aaargh, sorry. Looking at this again, I just found out that my `stable` branch still builds C++14 (and the `10_13` comes from the default `osx_image` value on Travis CI: Xcode 9.4.1, macOS 10.13; I wasn't setting `MACOSX_DEPLOYMENT_TARGET` yet, and the default Python is still 2, so I only have cibuildwheel 1.1.0, so that's why it's not being set for me either!). I'm trying again with a branch from before pybind11 v2.5.0, but hopefully everything will (not) work as expected!

If that's the explanation, I'll make that PR to update the docs to reflect that C++17 does not álways need 10.13/10.14 :-)

**Comment by Czaki** [comment]
> I wasn't setting `MACOSX_DEPLOYMENT_TARGET` yet, and the default Python is still 2, so I only have cibuildwheel 1.1.0, so that's why it's not being set for me either!)

I do not understand. Why this version of `cibuildwheel` block setting environment variable?

**Comment by YannickJadoul** [comment]
> I do not understand. Why this version of `cibuildwheel` block setting environment variable?

No, it doesn't. But I thought #306 was already released and forced `MACOSX_DEPLOYMENT_TARGET` if not set, but it only happens for Python 3.5 (#220).

**Comment by YannickJadoul** [comment]
@Czaki Alright, so now things do work as expected: https://travis-ci.org/github/YannickJadoul/Parselmouth-OSX-10.9/builds/680784378 (`travis` being a branch from before the update of pybind11 to v2.5.0, cfr. explanation above, and `master` being the one after). Sorry for confusing the different versions and comparing the wrong ones. And thanks for thinking along :-)

I'll see if I can make a PR tomorrow to update the docs, and I'll tag you once I have something!
