### ISSUE TITLE
Clear build directory between wheels

### ISSUE THREAD

**Issue by rnpridgeon** [joerick/cibuildwheel#353]
Pip 20.2, used by manylinux1, introduced a new build in place functionality. This results in artifact reuse which may result in corrupted manylinux wheels (abi flag mu with ucs2 only support). 

https://github.com/pypa/pip/issues/8165#issuecomment-624669107

pypa/pip#8165
pypa/manylinux#560

Cleaning out the build directory between builds should remedy this.

**Comment by joerick** [comment]
I hadn't actually read up on this bug properly. Yikes. I'm so grateful for the pip maintainers, and also glad I'm not one of them! :) 

Has this particular issue bitten you? If so, how? cibuildwheel 1.4.2, which was just released, uses manylinux wheels containing pip 20.1.1, which has reverted the build in-place change.

**Comment by mayeut** [comment]
@rnpridgeon,

FYI
The issue [has been fixed](https://github.com/joerick/cibuildwheel/issues/351) in cibuildwheel 1.4.2 by updating pinned manylinux images
Also, manylinux1:latest is now using pip 20.1.1 which reverted the behavior introduced in 20.1

There's now a test in cibuildwheel to check for a minimal build isolation by testing some unicode functions.
That being said, someone not using the pinned versions of manylinux provided by cibuildwheel might end up in a similar situation if pip breaks behavior in the future.
Another solution to this problem might be a good idea.

**Comment by rnpridgeon** [comment]
@joerick  Sure did, linked below. Thanks @mayeut!

https://github.com/confluentinc/confluent-kafka-python/issues/882

I'll bump up the cibuildwheel version to 1.4.2, thank you both.

**Comment by henryiii** [comment]
I think this was what was causing my segfaults, which I've been debugging today, and had pinned down to the manylinux2010 Python 2.7 builds. Saw this, updated to 1.4.2, and looks like it has built past the segfaults!
