### ISSUE TITLE
Support for building python3.9

### ISSUE THREAD

**Issue by fruch** [joerick/cibuildwheel#370]
it's almost going out of beta, but we can't build for it using cibuildwheel

**Comment by YannickJadoul** [comment]
Would be nice to have, yes! Is there a manylinux image containing it? And a nuget package?

**Comment by YannickJadoul** [comment]
Alright, I can already answer the second part of my own question: https://www.nuget.org/packages/python/3.9.0-b1

**Comment by YannickJadoul** [comment]
But manylinux doesn't seem to be available?

https://github.com/pypa/manylinux/blob/ac5df8a424d3f8743b8177be6722e609fd728d55/docker/build_scripts/build_env.sh#L5

See also pypa/manylinux#482

I think that's something to ask about upstream, if you want this in `cibuildwheel`? Once we have that, updating `cibuildwheel` should be reasonably painless.

**Comment by joerick** [comment]
Beta support has been added! Check out #382 for instructions for how to use.
