### ISSUE TITLE
PytestCollectionWarning: cannot collect test class 'TestProject' because it has a __init__ constructor

### ISSUE THREAD

**Issue by YannickJadoul** [joerick/cibuildwheel#372]
Shouldn't be too hard, but there's a warning in our test suite we should probably fix:

https://github.com/joerick/cibuildwheel/runs/732376574#step:6:40

```
 test/test_projects/base.py:10
  /home/runner/work/cibuildwheel/cibuildwheel/test/test_projects/base.py:10: PytestCollectionWarning: cannot collect test class 'TestProject' because it has a __init__ constructor (from: test/test_cpp_standards.py)
    class TestProject:

test/test_projects/base.py:10
  /home/runner/work/cibuildwheel/cibuildwheel/test/test_projects/base.py:10: PytestCollectionWarning: cannot collect test class 'TestProject' because it has a __init__ constructor (from: test/test_subdir_package.py)
    class TestProject:
```

If I understand correctly, pytest is trying to pick up `test_projects`/`TestProject` because it starts with test. We should probably just rename the class/directory or tell pytest to ignore it. Not sure what's the best way to do it, but I'll leave this here until someone has time to look into it, explore the different options, and make a PR (possibly myself, if I ever have some time and some of the other backlog gets cleaned up).

**Comment by Czaki** [comment]
Maybe blacklist dir with this: https://docs.pytest.org/en/latest/reference.html#collect-ignore ?

**Comment by YannickJadoul** [comment]
Seems good. Built-in to the test files rather than just a flag we could forget.

A bit annoying we have to create `conftest.py` just for that, but go ahead, if you want. I already have too many PRs and issues on my mind, for the moment.

**Comment by joerick** [comment]
According to some rough research, adding `__test__ = False` attribute to the class might disable it.

**Comment by YannickJadoul** [comment]
That might be even nicer!
