### ISSUE TITLE
How do I check if I'm in the docker?

### ISSUE THREAD

**Issue by msyriac** [joerick/cibuildwheel#380]
When building my project, I need to turn off "march=native" flags to make my binary portable, but I'd like to do this automatically only if I'm in the container where the wheel is being built. From experimenting, I've found that environment variables like $TRAVIS and $CIBW_PLATFORM are not set inside the cibuildwheel docker. The only way I could check was to look for the existence of "/.dockerenv", but this is a check that is not specific to cibuildwheel. (If someone else was building my package in a docker container, it isn't necessary that they are interested in portable binaries.) Is there a recommended way to check that I am in a cibuildwheel docker?

Here's what I do currently; note the comment:

```
# Only the last dockerenv check actually works for cibuildwheel                                                                                               
if [[ $TRAVIS ]] || [[ $CIBW_PLATFORM ]] || [ -f /.dockerenv ] ; then                                                                                         
    sed -i 's/march=native/march=x86-64/g' configure.ac                                                                                                       
else                                                                                                                                                          
    echo "Not replacing native with x86-64. Binary will not be portable."                                                                                     
fi
```

**Comment by YannickJadoul** [comment]
Is there a reason you're not doing that for Windows/macOS builds, and why you couldn't just add this `sed -i` line to `CIBW_BEFORE_BUILD`? Otherwise, if you just want to do if for Linux, then put it in `CIBW_BEFORE_BUILD_LINUX`?

The thing is, cibuildwheel wants to try and hide this docker image from you as much as possible. So is this per se related to being in a docker image, or just to building portable wheels?

**Comment by YannickJadoul** [comment]
Also, if you add a variable to `CIBW_ENVIRONMENT`, it will be set in the environment `cibuildwheel` will run the build command in, so you could test for running in `cibuildwheel` in that way.

**Comment by YannickJadoul** [comment]
> Also, if you add a variable to `CIBW_ENVIRONMENT`, it will be set in the environment `cibuildwheel` will run the build command in, so you could test for running in `cibuildwheel` in that way.

Even better than this: [as documented](https://cibuildwheel.readthedocs.io/en/stable/options/#examples_1), `CIBUILDWHEEL` will be set in the `cibuildwheel` environment.

**Comment by msyriac** [comment]
I can't do it in `CIBW_BEFORE_BUILD` (easily), because the file 'configure.ac' only appears much later after a series of other operations initiated by setup.py. We don't intend to support Windows, but I thought the above would work for macOS (the travis build is still running, so I haven't confirmed)... is there some reason why it wouldn't?

`CIBUILDWHEEL` seems like exactly what I need though, thanks!

**Comment by YannickJadoul** [comment]
> I can't do it in `CIBW_BEFORE_BUILD` (easily), because the file 'configure.ac' only appears much later after a series of other operations initiated by setup.py

Aah, yes, ok :-)

> is there some reason why it wouldn't?

Ah, no, but I was just thinking that there had to be a better way than explicitly detecting whether you're in the docker image. It seemed more a property of making portable wheels than of the docker image. But then `CIBUILDWHEEL` will provide what you need in a portable way, I suppose :-)

**Comment by msyriac** [comment]
Yes, I totally missed that in the docs! Thanks, closing.
