### ISSUE TITLE
Add CircleCI support for Windows

### ISSUE THREAD

**Issue by ixje** [joerick/cibuildwheel#381]
CircleCI now supports Windows (including on the free plan)
https://circleci.com/docs/2.0/hello-world-windows/#prerequisites

**Comment by YannickJadoul** [comment]
I have good hopes this will already work, given that we already support other platforms on CicleCI and already support Windows on other CI providers. So hoooopefully we'd just add it to our CI config and to our docs :-)

I can have a look tomorrow or Wednesday.

**Comment by YannickJadoul** [comment]
See https://github.com/joerick/cibuildwheel/pull/385
