### ISSUE TITLE
OSError: [WinError 17] The system cannot move the file to a different disk drive

### ISSUE THREAD

**Issue by alexlib** [joerick/cibuildwheel#388]
```
 File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\cibuildwheel\windows.py", line 286, in build
    repaired_wheel.replace(options.output_dir / repaired_wheel.name)
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\pathlib.py", line 1338, in replace
    self._accessor.replace(self, target)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\cibuildwheeli4q9t16s\\repaired_wheel\\OpenPIV-0.21.9a0-cp36-cp36m-win_amd64.whl' -> 'wheelhouse\\OpenPIV-0.21.9a0-cp36-cp36m-win_amd64.whl'
##[error]Process completed with exit code 1.
```

**Comment by Czaki** [comment]
Which CI?

@joerick So it looks like shutil move should be used again. 

@alexlib downgrade to version 1.4.2 until 1.5.1 will be released

**Comment by alexlib** [comment]
Github actions 

suggested to change this line 

https://github.com/joerick/cibuildwheel/blob/41891277d33c728059fb89ac2ce0c2b32d6d459b/cibuildwheel/windows.py#L286

to 

https://docs.python.org/3/library/shutil.html#shutil.move

similar to the same bug noticed here https://github.com/k4yt3x/video2x/issues/249

**Comment by Czaki** [comment]
I wrote about this. I do not understand why current test set doe not catch this. 

https://github.com/joerick/cibuildwheel/runs/802745957?check_suite_focus=true

This is result of refactoring from #376

**Comment by YannickJadoul** [comment]
Weird indeed, that our tests work with this. I thought we had reasonable coverage :-/

**Comment by Czaki** [comment]
It may depend on machine which is selected by CI provider. So it may happen rarely. or even it could be self hosted runner.

**Comment by YannickJadoul** [comment]
Alright. Well, at least we noticed when making the change, so we don't need to debug for ages :-)

Does that also mean that just rerunning the job might help @alexlib, for now?

**Comment by alexlib** [comment]
It failed several times on the same line, not once.

**Comment by joerick** [comment]
Fix released in v1.5.1!

**Comment by henryiii** [comment]
Was it supposed to have been tagged?

**Comment by joerick** [comment]
Apologies, forgot to push tags! Should be there now.
