### ISSUE TITLE
Multiple CIBW_TEST_COMMAND commands not supported on macOS

### ISSUE THREAD

**Issue by hroncok** [joerick/cibuildwheel#39]
I have the following:

      - CIBW_TEST_COMMAND='cd {project}; python -m pytest -v test'

And on Linux, it works, but on macOS, it's broken, because:

```pycon
>>> shlex.split('cd foo; python -m pytest -v test')
['cd', 'foo;', 'python', '-m', 'pytest', '-v', 'test']
```

And

```console
$ cd '/Users/travis/build/admesh/python-admesh;' python -m pytest -v test
/usr/bin/cd: line 4: cd: /Users/travis/build/admesh/python-admesh;: No such file or directory
```

I will now fix my tests not to assume running from the projects directory and will workaround this, but there might be more use cases, where multiple CIBW_TEST_COMMAND commands are desired.

**Comment by joerick** [comment]
Agreed, this should run in a shell, similar to CIBW_BEFORE_BUILD. Should be a simple fix, PR welcome :)

**Comment by hroncok** [comment]
Once I make my test pass and my macOS wheels to build, I'll have a look at this.
