### ISSUE TITLE
How to use Travis to upload ARM/PowerPC?

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#400]
Hi, my alternative arch release failed on Travis, since even the built-in deploy seems to try to install the deploy requirements, and fails due to not having wheels, so trying to build, and then having a permissions error in `~/.cache`

See https://travis-ci.com/github/scikit-hep/boost-histogram/jobs/358099342 for an example.

I've tried manually installing/upgrading these first to see if that helps, but it still fails. Does anyone have experience getting the files out of Travis, ideally using the built in support and/or Twine?

PS: PowerPC worked when I moved the pip install, ARM still has an issue. https://travis-ci.com/github/scikit-hep/boost-histogram/jobs/358642879

**Comment by Czaki** [comment]
It looks like problem with directory permission. 
You may add ls to you yaml file. Or if you have edu account you can make private copy and ssh to machine (travis does not allow this for public repo)

You can also try `--no-build-isolation` flag which disable pep 517.

**Comment by henryiii** [comment]
Thanks! I fixed it by adding a `sudo rm -r $HOME/.cache` at the start of the job, so it was a directory issue - probably related to Travis installing some things before the build and not clearing the cache folder. If there's a spot in the docs where this would be possible to add in a suggestion, it might be helpful, otherwise it can be closed.

**Comment by joerick** [comment]
Our examples use `twine` directly, so there's nowhere obvious to put it in our docs. It's probably worth a bug report to Travis themselves, as it sounds like a bug. If you add the log with error message to your original post  other people with the same issue might find their way here. Thanks for letting us know!
