### ISSUE TITLE
[BUG] Pyproject.toml workaround can make a file

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#421]
The following pyproject.toml on Windows:

```toml
requires = [
  "setuptools_scm[toml]>=4.1.2"
]
```

produces a file

```
4.1.2
```

which breaks the setuptools_scm versioning, since it's now a dirty directory. Illustrated in #420. I think it used to work originally, as I made a few releases after the Windows 3.5 patch initially went in.

This _only_ breaks if there is a bracketed requirement.

**Comment by Czaki** [comment]
It breaks on all windows python version or only python 3.5?

**Comment by YannickJadoul** [comment]
#420 shows all Windows versions broken, it seems.

**Comment by henryiii** [comment]
Once it breaks, the file stays there and continues to break the others. But it's only 3.5, I believe. The test solution in #420 is faulty, it's not the right way to escape this.
