### ISSUE TITLE
shutil.error moving repaired wheels to output dir in MacOS and Windows

### ISSUE THREAD

**Issue by mondeja** [joerick/cibuildwheel#435]
I'm experiencing this error in MacOS builds:

```
Traceback (most recent call last):
  File "/usr/local/bin/cibuildwheel", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cibuildwheel/__main__.py", line 238, in main
    cibuildwheel.macos.build(build_options)
  File "/usr/local/lib/python3.7/site-packages/cibuildwheel/macos.py", line 275, in build
    shutil.move(str(repaired_wheel), options.output_dir)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 564, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'wheelhouse/polf-0.0.7-cp36-cp36m-macosx_10_9_x86_64.whl' already exists
```

...and the same for Windows:

```
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\cibuildwheel.exe\__main__.py", line 9, in <module>
  File "c:\python38\lib\site-packages\cibuildwheel\__main__.py", line 236, in main
    cibuildwheel.windows.build(build_options)
  File "c:\python38\lib\site-packages\cibuildwheel\windows.py", line 307, in build
    shutil.move(str(repaired_wheel), options.output_dir)
  File "c:\python38\lib\shutil.py", line 778, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'wheelhouse\polf-0.0.7-cp36-cp36m-win32.whl' already exists
```

- [Build logs](https://travis-ci.com/github/mondeja/cpolf/builds/185425742)

### Configuration file (TravisCI)

```yml
language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

env:
  global:
    # cpolf only works on Python >= 3.6.
    - CIBW_BUILD="cp36-* cp37-* cp38-*"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/test -svv"
    - CIBW_ENVIRONMENT="DEBUG='1'"
    - TWINE_USERNAME=__token__

install:
  - pip3 install --upgrade cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
  # Upload to PyPI on tags
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing wheelhouse/*.whl
    fi
```

Seeing [`shutil.move` docs](https://docs.python.org/3/library/shutil.html#shutil.move) I've found that says "If the destination already exists but is not a directory, it may be overwritten depending on os.rename() semantics." So  `shutil.move` does not necessarily overwrite files when moving.

I've seen that comments in source code points  "we're all done here; move it to output (remove if already exists)" ([here](https://github.com/joerick/cibuildwheel/blob/fac9b133075fc44dd2fb2041958b5468ff583f77/cibuildwheel/macos.py#L274) and [here](https://github.com/joerick/cibuildwheel/blob/fac9b133075fc44dd2fb2041958b5468ff583f77/cibuildwheel/windows.py#L306)), but that's not true for `shutil.move`.

**Comment by YannickJadoul** [comment]
So, are you starting out with wheels already in that directory? Could you show us the full build, or build config, or some more information?

**Comment by mondeja** [comment]
Sorry, I forgot the link [here it is](https://travis-ci.com/github/mondeja/cpolf/builds/185425742).

**Comment by YannickJadoul** [comment]
Thanks!

I do not know why, but Travis CI is running your commands twice, so also `$ cibuildwheel --output-dir wheelhouse` is run twice:

- https://travis-ci.com/github/mondeja/cpolf/jobs/387582076#L91
- https://travis-ci.com/github/mondeja/cpolf/jobs/387582076#L689

And the second time, the output files already exist, and you get this error. This might be a bug in Travis CI or so; I don't know why this is happening, as I don't immediately see a problem in your configuration...

**Comment by YannickJadoul** [comment]
This might be related? https://travis-ci.community/t/build-config-running-twice/6985

**Comment by mondeja** [comment]
> I do not know why, but Travis CI is running your commands twice

Yes, the configuration is also duplicated. Thanks for clarify this :+1:

**Comment by YannickJadoul** [comment]
But you have something very close to the example configuration in `cibuildwheel`'s README, so if there's something wrong there, please let us know! :-)

**Comment by mondeja** [comment]
I think that the wrong thing in relation to the behavior of these failures in the CIs are these two source code comments, that are confusing. Otherwise all right :+1:
