### ISSUE TITLE
"dyld: Library not loaded libffi.6.dylib" on GitHub "macos-latest"

### ISSUE THREAD

**Issue by anka-213** [joerick/cibuildwheel#446]
Here is a full log: https://github.com/anka-213/gf-core/runs/1227241373?check_suite_focus=true
```
$ python -m cibuildwheel src/runtime/python --output-dir wheelhouse
     _ _       _ _   _       _           _
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|

cibuildwheel version 1.6.1
...
+ Download https://downloads.python.org/pypy/pypy2.7-v7.3.1-osx64.tar.bz2 to /tmp/pypy2.7-v7.3.1-osx64.tar.bz2
+ tar -C /tmp -xf /tmp/pypy2.7-v7.3.1-osx64.tar.bz2
+ which python
/tmp/cibw_bin/python
+ python --version
dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /private/tmp/pypy2.7-v7.3.1-osx64/bin/libpypy-c.dylib
  Reason: image not found
```

It seems like the hard coded version of pypy (`pypy2.7-v7.3.1-osx64`) depends on an older version of `libffi`, than the latest version: `libffi.7`.

----

It does however look like the the latest version of pypy ([v7.3.2, which fixes it]( 
https://doc.pypy.org/en/latest/whatsnew-pypy2-7.3.2.html)) is in the repo, I just need to wait for the next release.
https://github.com/joerick/cibuildwheel/blob/9fbe8186f97802a3df4dd6ff24c423da7d68c0fd/cibuildwheel/macos.py#L43-L45

Is there anything I can do in the meantime?

**Comment by YannickJadoul** [comment]
Not that I'm aware of. Can you use our `master`, until we have a release (soon, we should, though; at least, I thought @joerick was planning one?).

**Comment by anka-213** [comment]
How do I use master?

**Comment by YannickJadoul** [comment]
Like this: `pip install git+https://github.com/joerick/cibuildwheel.git@master`
Or if you want to pin to a specific commit (e.g., currently the latest on master), then try `pip install git+https://github.com/joerick/cibuildwheel.git@f6eaa9f`

**Comment by anka-213** [comment]
Yes, that worked. Thanks!

**Comment by YannickJadoul** [comment]
Good, I'll close this, if that's OK with you? If you keep an eye on the cibuildwheel releases, woon enough, there should be a new version, and you can revert to installing that release :-)

**Comment by henryiii** [comment]
By the way, @joerick , currently releases are only made by adding a tag, and no one makes a "GitHub release". That would a) notify watchers that a new release is available (I watch all the projects I use, at least in "releases only" mode or by using the RSS feed in Feedly), and b) show a nice pretty current release tile on the main page. I can setup a CI job (think, I haven't tried before)  that makes a "GitHub release" whenever you tag in the form "v*", or could you (or one of us, I can do it) manually make a "GitHub release" whenever a new tag shows up. I could even go over the old tags and make releases out of them if you'd like, copying the changelog entry into the description. Thoughts?

Current:
<img width="352" alt="Screen Shot 2020-10-08 at 6 10 24 PM" src="https://user-images.githubusercontent.com/4616906/95518785-cbdb8000-0991-11eb-8ab0-760189cbee72.png">

Example from a repo with GitHub releases:
<img width="331" alt="Screen Shot 2020-10-08 at 6 11 40 PM" src="https://user-images.githubusercontent.com/4616906/95518788-ced67080-0991-11eb-97e8-27831f33c2ab.png">

**Comment by henryiii** [comment]
PS: On my packages I normally have the CI make a PyPI release whenever a GitHub release is made, via a `__token__` (something like [this](https://scikit-hep.org/developer/gha_pure)), but that's not what I'm proposing here; just manually or automatically making "GitHub releases" whenever a new tag is made (and ideally released on PyPI)

**Comment by anka-213** [comment]
It might be worth pinning this issue, since, unless I'm mistaken, more or less every single user of this project will run into this problem. (Otoh, they should still find it when googling the error message)

**Comment by joerick** [comment]
I just released 1.6.2 containing this Pypy upgrade.

**Comment by joerick** [comment]
> By the way, @joerick , currently releases are only made by adding a tag, and no one makes a "GitHub release". That would a) notify watchers that a new release is available (I watch all the projects I use, at least in "releases only" mode or by using the RSS feed in Feedly), and b) show a nice pretty current release tile on the main page. I can setup a CI job (think, I haven't tried before) that makes a "GitHub release" whenever you tag in the form "v*", or could you (or one of us, I can do it) manually make a "GitHub release" whenever a new tag shows up. I could even go over the old tags and make releases out of them if you'd like, copying the changelog entry into the description. Thoughts?

Ah, I thought that pushing a tag would create the release.  Funnily enough, I've been working on-and-off to create a tool to automate stuff like this as well. Until that's ready I'll try to copy-paste the changelog into Github releases as part of my release workflow :)

**Comment by henryiii** [comment]
Thanks! Huge improvement, much nicer page, and I got the notification! :)

**Comment by henryiii** [comment]
I like your emojis, by the way. :)

**Comment by YannickJadoul** [comment]
> Thanks! Huge improvement, much nicer page, and I got the notification! :)

Yes, indeed. I got the notification too. Never realized, but indeed, I never got email of the actual release :-)
