### ISSUE TITLE
Suggestion: allow alternate Docker images

### ISSUE THREAD

**Issue by jbarlow83** [joerick/cibuildwheel#45]
For my workflow I need to install a C++14 capable compiler onto the manylinux1 image, then build a C++ library with that compiler, then link my pybind11 project against the library. (I may not be sane.)

Parselmouth does something similar. It imports a version of gcc-7.2 toolchain built for centos5,  compiles ccache, aims ccache at the /host directory and then calls cibuildwheel. This allows both the newer compiler and then by statically linking libstdc++ the ABI should be compatible.

I am thinking it might be better to fork the official manylinux1 image and install what I need. The dependencies don't change often. If so, I'd need an option to use different Docker images, which doesn't look hard to add.

Do you think swapping out the quay.io images actually makes sense for my use case or are there reasons I shouldn't do that?

**Comment by joerick** [comment]
Yeah, a different docker image seems like a sensible option. Note the PyPA images have i686 and x86_64 variants, so you'd need to make variants for both. PR welcome!

**Comment by YannickJadoul** [comment]
Thanks for the idea; I had never thought about it, but it might indeed be a good idea to 'subclass' the manylinux docker images (e.g. in Parselmouth).

I don't think the PR should be that hard, so if you'd like, I could have a quick look at it, too?

**Comment by YannickJadoul** [comment]
I've started implementing something. Feel free to look along and correct me at #46!

**Comment by joerick** [comment]
This is completed in d16c63ad95e845c0c0e97b05c8730786002ddefa
