### ISSUE TITLE
Trouble with running on Appveyor

### ISSUE THREAD

**Issue by lelit** [joerick/cibuildwheel#450]
Since some time I'm [facing a failure](https://ci.appveyor.com/project/lelit/python-rapidjson/builds/35931765) at the setup stage of job on Appveyor: I understand this is most probably unrelated to cibuildwheel, but maybe somebody has an explanation/cure?

**Comment by lelit** [comment]
... or even a better place to ask?

**Comment by joerick** [comment]
Looks like your Appveyor job is trying to run cibuildwheel with Python 3.5 - we dropped support for that a while back. 

Try updating that to something more modern. Don't worry, it won't affect the versions of Python that you can build wheels for!

**Comment by lelit** [comment]
Oh, I see! I'm going to try right now, thank you!

**Comment by lelit** [comment]
That was it, thanks again!
