### ISSUE TITLE
Output_dir not always honored

### ISSUE THREAD

**Issue by kcpevey** [joerick/cibuildwheel#451]
Thank you for this great package! 

I've been working out how best to construct my github action that builds a bunch of wheels for a variety of architectures. It seems from the output that I'm successfully generating wheels, but they are not being moved to the output directory properly. I've gone through several iterations of my gh action yml file and I know I've seen it move the wheel to the output dir properly at some point, but with my current setup, it no longer does that. 

Are there any special requirements for using output_dir? Like only running one wheel at a time?

The bash section of my action that runs `cibuildwheel`:
```
         RUNNER_OS="${{ runner.os }}"
          PLATFORM="${{ matrix.platform }}"
          PYTHON_VERSION="${{ matrix.python-version }}"
          echo $RUNNER_OS
          echo $PLATFORM
          echo $PYTHON_VERSION

          if [ "$RUNNER_OS" == "Windows" ]; then
            if [ "$PLATFORM" == "x64" ]; then
              if [ "$PYTHON_VERSION" == "3.6" ]; then
                export CIBW_BUILD="cp36-win_amd64"
              elif [ "$PYTHON_VERSION" == "3.7" ]; then
                export CIBW_BUILD="cp37-win_amd64"
              elif [ "$PYTHON_VERSION" == "3.8" ]; then
               export CIBW_BUILD="cp38-win_amd64"  
              fi
            elif [ "$PLATFORM" == "x32" ]; then
              export CIBW_BUILD="cp36-win32 cp37-win32 cp38-win32"
            fi

          elif [ "$RUNNER_OS" == "Linux" ]; then
            if [ "$PLATFORM" == "x64" ]; then
              export CIBW_BUILD="cp36-manylinux_x86_64 cp36-manylinux_aarch64 cp36-manylinux_ppc64le cp36-manylinux_s390x"
            elif [ "$PLATFORM" == "x32" ]; then
              export CIBW_BUILD="cp36-manylinux_i686"
            fi
          elif [ "$RUNNER_OS" == "macOS" ]; then
            export CIBW_BUILD="cp36-macosx_x86_64"
          fi
          echo $CIBW_BUILD
          python -m cibuildwheel --output-dir wheelhouse
```

The actual action where the wheels are built, but not moved to `output_dir` and therefore not picked up as `artifacts`: https://github.com/Quansight/numpy-threading-extensions/runs/1315726066?check_suite_focus=true

**Comment by Czaki** [comment]
You have artifact upload action before you call `cibuildwheel`. After build wheel you call checkout action.

**Comment by kcpevey** [comment]
Ah. I mistakenly moved that.. Thank you so much for catching that!
