### ISSUE TITLE
Windows: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by rmk135** [joerick/cibuildwheel#452]
Hello,

Can you, please, help me to debug https://travis-ci.org/github/ets-labs/python-dependency-injector/jobs/739050288?

It occurs only on Windows. Error says: ``urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>``. I'm unclear whos certificate has expired.

Best,
Roman

**Comment by Czaki** [comment]
Please bump cibuildwheel to the most recent version. it should be fixed in #447

**Comment by rmk135** [comment]
Got it, will try. Thank you.

**Comment by jcrist** [comment]
I'm currently seeing this as well on travis ci windows builds only, already running the latest version (1.6.3). I did a release yesterday and things worked fine, so somethings changed in the last day (likely the certs on the windows box).

I've worked around this by installing `certifi` and configuring the build to use certifi's certs, see here:

https://github.com/jcrist/quickle/pull/58/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R31

**Comment by rmk135** [comment]
@jbarlow83 , cool, thanks for sharing.

**Comment by Czaki** [comment]
oh. So it is outdated certif on this python 
Could you try to bump python version in travis file from 3.8.0 to 3.8.2 
```
        - choco install python --version 3.8.2
```

@jcrist  @rmk135?

**Comment by jcrist** [comment]
I'm already using 3.8.6 (in that PR), which didn't fix things. Installing certifi and forcing the build to use certifi certs did fix things.

**Comment by Czaki** [comment]
starnge

**Comment by rmk135** [comment]
Fixed `python3: command not found` by adding a line from README into `before_install`:

```
      - ln -s /c/Python38/python.exe /c/Python38/python3.exe
```

Seems that wasn't needed when I initially configured windows builds.

**Comment by rmk135** [comment]
Thanks everybody for the help and special thanks to this lib creators and contributors for the great tool.

**Comment by joerick** [comment]
I just spotted this in an unrelated PR, this time on Appveyor:

https://ci.appveyor.com/project/joerick/cibuildwheel/builds/36032538/job/n4duoutlja3nbqit

**Comment by jcrist** [comment]
Perhaps cibuildwheel should require `certifi` as a dependency and explicitly use certifi's certs in e.g. `download` instead of relying on the system certs? `requests` does this, and it seems to work well.

**Comment by Czaki** [comment]
It looks rather like outdated windows images from CI provider. There is possibility to change certificate source after scripts run?

**Comment by mayeut** [comment]
I got the same issue on one of my projects on Appveyor...
I proposed a PR based on @jcrist comment. It seems like a good solution (if it works, but I don't doubt it will. Let's wait for PR CI status).

**Comment by joerick** [comment]
This is fixed in v1.6.4.

**Comment by henryiii** [comment]
@joerick no GitHub release?

**Comment by joerick** [comment]
@henryiii oops, thanks for the reminder!
