### ISSUE TITLE
TLS broken when building for PyPy on Travis MacOs

### ISSUE THREAD

**Issue by fruch** [joerick/cibuildwheel#457]
I've switch today to `1.6.4`, and PyPy builds on mac fails for me on travis:
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/wheel/
```
https://travis-ci.org/github/scylladb/python-driver/jobs/740631922

CPython with exact same configuration was building o.k.:
https://travis-ci.org/github/scylladb/python-driver/jobs/740631921

**Comment by henryiii** [comment]
Is this still a problem? I think we test this?

**Comment by Czaki** [comment]
If I good remember this was fixed.

**Comment by henryiii** [comment]
Reopen if it was not! :)
