### ISSUE TITLE
Add GitHub discussions

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#480]
I think enabling discussions (added for everyone today) could be really useful. Especially the show and tell category would be interesting. You can move issues into discussions.

https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/

**Comment by joerick** [comment]
Sounds good! Yes that could be useful for the more support-oriented issues we get, and the open-ended long-running discussions. I'll enable it and we can see what we think.
