### ISSUE TITLE
Manylinux PyPy3.6 Broken?

### ISSUE THREAD

**Issue by ax3l** [joerick/cibuildwheel#487]
Originally reported [here](https://github.com/pypa/manylinux/issues/899), I think the `pp36-manylinux_x86_64` images are currently broken.

First seen today, I get yum issues in the `pp36-manylinux_x86_64` image of the form
```
  + yum -y install glibc-static tar
  Error: Cannot find a valid baseurl for repo: base
  Loaded plugins: fastestmirror, ovl
  Determining fastest mirrors
  YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
   Eg. Invalid release/repo/arch combination/
  removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
  Loaded plugins: fastestmirror, ovl
  Setting up Install Process
  Loading mirror speeds from cached hostfile
  YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
   Eg. Invalid release/repo/arch combination/
  removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
```

during my builds with [cibuildwheel](https://github.com/joerick/cibuildwheel). Is this a known issue? I could not find a similar report yet.

My corresponding logic is this: https://github.com/openPMD/openPMD-api/tree/2e74a7b995d6d0a121d0cf59af62e6b44913a9d4 and I see it during an update to `cibuildwheel==1.7.1`: https://github.com/openPMD/openPMD-api/pull/852

Is this known? Is there an alternative pp manylinux or manylinux2010/2014 image one could use? `pypywheels` has a couple of tags, but so far I used the default (and don't know what it did correspond to): https://hub.docker.com/u/pypywheels Maybe it's also just the ancient centos mirrors that it uses that were turned off or so?

**Comment by mattip** [comment]
It may have been a temporary glitch? Does the error repeat if you retrigger the build?

**Comment by mayeut** [comment]
The image pinned in cibuildwheel 1.7.1 has been built pre-EOL of CentOS-6:
https://github.com/joerick/cibuildwheel/blob/d83daa3958a9809f0b03fe125ce28d1f52ab7f14/cibuildwheel/resources/pinned_docker_images.cfg#L12

c.f. https://github.com/pypy/manylinux/issues/13 which end up in the related PR to the rebuild of the image that fixed mirror issues in the base image for post-EOL (base image being `manylinux2010_x86_64` which has been updated in `cibuildwheel` 1.7.1 for this same issue on cpython builds #472 ).

@ax3l 
If you try with `CIBW_MANYLINUX_PYPY_X86_64_IMAGE=pypywheels/manylinux2010-pypy_x86_64:2020-12-11-f1e0e80`, I think it should work while waiting for an update of `cibuildwheel`.

cc @joerick, can you trigger an update of dependencies ?

**Comment by joerick** [comment]
> cc @joerick, can you trigger an update of dependencies ?

I just updated to Big Sur and am having troubles with old versions of Python on my machine 🙄  perhaps @henryiii could run `bin/make_dependency_update_pr.py`?

**Comment by mayeut** [comment]
> I just updated to Big Sur and am having troubles with old versions of Python on my machine 🙄

Same here...

Maybe I can propose a manual GHA workflow that we can use to trigger those updates ? would that work for you @joerick ?

**Comment by joerick** [comment]
Sounds great @mayeut!

**Comment by henryiii** [comment]
I'm on Big Sur too, but my pyenv environments seem to be fine.

**Comment by joerick** [comment]
Assuming fixed.
