### ISSUE TITLE
[idea] Parse valid PyPy links from versions.json and always build PyPy with manylinux2010+

### ISSUE THREAD

**Issue by mattip** [joerick/cibuildwheel#488]
Two ideas to make the PyPy experience nicer:
- Like github actions, get the latest PyPy versions from https://downloads.python.org/pypy/versions.json
- Never use manylinux1 for linux wheels on PyPy, since it is not supported.

**Comment by Czaki** [comment]
But the idea of cibuildwheel is to pin the build process to a specified version to get reproducibility. Or you think about an update script?

**Comment by YannickJadoul** [comment]
>    * Like github actions, get the latest PyPy versions from https://downloads.python.org/pypy/versions.json

@Czaki makes a good point here. Also, we try to have the same version for all OSes, and we do always need a new manylinux image, for each release.

I agree it would be nice, though, if something can be automated here! But we'd need to find a balance between ease of use and reproducibility (cfr. #239 & #256).

>    * Never use manylinux1 for linux wheels on PyPy, since it is not supported.

I believe we already don't do this. We only have a `manylinux2010` in `pinned_docker_images.cfg`:
https://github.com/joerick/cibuildwheel/blob/d83daa3958a9809f0b03fe125ce28d1f52ab7f14/cibuildwheel/resources/pinned_docker_images.cfg#L11-L12

Users can overwrite this by setting the `CIBW_MANYLINUX_PYPY_X86_64_IMAGE` environment variable, though, but only setting it to `manylinux2010` (or leaving it empty) will result in `cibuildwheel` using an official PyPy image.

**Comment by henryiii** [comment]
I think this is resolved as of #496.
