### ISSUE TITLE
[question] Running aarch_64 builds on Github Actions using docker's multi-cpu architecture support

### ISSUE THREAD

**Issue by tasn** [joerick/cibuildwheel#513]
Has anyone tried doing this? Or maybe even something like this: https://github.com/uraimo/run-on-arch-action

Thanks for this great project, it's been a blessing! I'm just trying to recover from Travis pulling the plug on OSS projects without notice.

**Comment by Czaki** [comment]
There was already a merged implementation https://github.com/joerick/cibuildwheel/pull/482. Here documentation https://cibuildwheel.readthedocs.io/en/latest/options/#archs. 
It is not available in PyPi version, but you could install it from the master.

**Comment by tasn** [comment]
Looks like I didn't search well enough. Sorry for the noise, and thanks!

**Comment by henryiii** [comment]
> I'm just trying to recover from Travis pulling the plug on OSS projects without notice.

There was a _little_ notice. https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by tasn** [comment]
Community gossip is not a notice, and anyhow, that was after the fact, not before. Obviously my builds stopped working a while back already, it's just that only now I found the time to address it.

**Comment by henryiii** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Did your builds stop working on travis-ci.com, or travis-ci.org? I'm trying to tell if the latter has been put into read-only mode yet, as I've been spending the last month moving the rest of my projects off of it, I'm not really sure if I have any left to tell. I thought I heard they had delayed the kill switch by a week or so, but not sure.

**Comment by tasn** [comment]
Blog posted on November 2nd for changes effective November 2nd, so again, not a notice.

Builds on travis-ci.com.

**Comment by henryiii** [comment]
Yes, agree on that one.

**Comment by YannickJadoul** [comment]
And to say I was quite sceptical when moving towards GHA, and thought "Should I really go with the big company? Poor Travis CI has been supporting OS so nicely."...

**Comment by tasn** [comment]
I get them, it's probably super expensive to run all of this CI. The only thing I'm annoyed with is the lack of notice.
