### ISSUE TITLE
README inconsistent in the listing of supported CI platforms

### ISSUE THREAD

**Issue by brettcannon** [joerick/cibuildwheel#531]
1. "currently it supports GitHub Actions, Azure Pipelines, Travis CI, AppVeyor, and CircleCI"
2. "Builds manylinux, macOS and Windows wheels for CPython and PyPy using Azure Pipelines, Travis CI, AppVeyor, and CircleCI"
3. "cibuildwheel currently works on Travis CI, Azure Pipelines, AppVeyor, GitHub Actions, CircleCI, and Gitlab CI"

I'm happy to submit a PR that either dedups all of these listings or at least makes them consistent, but since none of the lists agree with each other I'm not sure who is right. 😅

**Comment by YannickJadoul** [comment]
Whoops :-D

The union of all should work, I believe (though Gitlab CI is not tested in CI, but was tested at some point: #419; and Travis CI ... well, yeah, let's not talk about that).

**Comment by henryiii** [comment]
It's listed in too many places, I think, it's easy to add one and not add it everywhere. :facepalm: The table is the canonical location for the correct list. `cibuildwheel` is really not very dependent on what CI system is used, it's just a Python package. It installs to system locations when running (and not targeting Linux) Windows and macOS, so it's not ideal to run locally, but all the CI platforms are about the same; there is a little bit of customization if the CI system is known (basically, it auto-detects the OS and enables log folding if a known CI system is detected, I think that's about it).

**Comment by YannickJadoul** [comment]
> `cibuildwheel` is really not very dependent on what CI system is used, it's just a Python package.

The main thing is the automatic detection of the CI system (cfr. `detect_ci_provider()`). That's kind of the switch we tend to pull once we've tested that everything works on that system. Other things _might_ work, but no guarantees, and you'll have to pass `--platform` yourself (which signals that it's not guaranteed to be supported).

**Comment by Czaki** [comment]
@joerick Did you change some access data:

```
Pull mirroring failed 3 weeks ago.
Repository mirroring has been paused due to too many failed attempts, and can be resumed by a project maintainer.
Last successful update 3 weeks ago. 
```

https://gitlab.com/joerick/cibuildwheel/

**Comment by joerick** [comment]
Thanks @Czaki, I didn't realise that had failed. I don't know when Gitlab stopped running CI, lemme see if I can fix that.

**Comment by joerick** [comment]
I can't claim to understand the Gitlab mirroring problems, but I clicked some things and it seems to be working again.

https://gitlab.com/joerick/cibuildwheel/-/pipelines/240710577

**Comment by brettcannon** [comment]
I will try and create a PR that cleans up the wording so the table in the README can be the canonical and only source of truth of what CI platforms are supported.

**Comment by joerick** [comment]
Thanks! But @henryiii is already working on it in https://github.com/joerick/cibuildwheel/pull/532
