### ISSUE TITLE
instaling problem on pypy manylinux

### ISSUE THREAD

**Issue by Czaki** [joerick/cibuildwheel#533]
I found another error in pypy. This time I create an issue https://foss.heptapod.net/pypy/pypy/-/issues/3382. If I got information about how to patch this I will create a patch for pypy.

**Comment by henryiii** [comment]
I'll suggest something, can you see if it fixes it?.

**Comment by henryiii** [comment]
@Czaki I think that https://github.com/Blosc/python-blosc/pull/243 should fix it.

**Comment by henryiii** [comment]
Assuming I can type without loosing chars...

**Comment by Czaki** [comment]
I assume that this is a problem with pypy because this `setup.py` works on macos. But I see that they forgot to close the file.

**Comment by henryiii** [comment]
PyPy's garbage collector is more expensive than CPythons, so it runs less often, IIRC.

**Comment by henryiii** [comment]
Feel free to comment on the issue in PyPy, I don't want to have to set up an account. ;)

**Comment by Czaki** [comment]
Thanks for help. I close the issue with adding a comment.
