### ISSUE TITLE
A BEFORE_BUILD command that's run only once per build environment

### ISSUE THREAD

**Issue by cbrown1** [joerick/cibuildwheel#54]
What is the right way to build (make && make install) dependencies only once at the beginning? If I run a script in CIBW_BEFORE_BUILD, everything gets built for every py version etc.

**Comment by joerick** [comment]
Excellent question. This could be a feature request, I think. What's your exact use-case - are you building a library that then gets linked in to a python extension perhaps?

For now, on Mac/Linux you might get away with `CIBW_BEFORE_BUILD="if [ ! -f built-lib ]; then make && make install && touch built-lib; fi"`, but I can see that's a little bit hacky.

Would you need the build architecture as a parameter to that as well (32 vs 64 bit)? They're built in the same build environment on Windows, there's a little jiggery-pokery with environment variables to make that work.

**Comment by cbrown1** [comment]
Yes, that is exactly my usecase. I have to build portaudio and libsndfile both, and link to them in my extension. 

I assume I would need the arch. I don't really know how auditwheel works or what it does, but it seems to include the libs although I haven't gotten that far yet. I could be wrong.

Thanks.

**Comment by joerick** [comment]
Yeah I guess you'd need the right build architecture as well for that. Luckily, we have [just the script](https://raw.githubusercontent.com/ogrisel/python-appveyor-demo/09a1c8672e5015a74d8f69d07add6ee803c176ec/appveyor/run_with_env.cmd) to set that up, so as long as your makefile tries to use Microsoft compilers you should be okay. The linux build uses 32/64 bit docker containers so they should compile for the active platform.

So yes, this looks like a feature request. But you could maybe work around using:

    CIBW_BEFORE_BUILD="if [ ! -f built-lib]; then make && make install && touch built-lib; fi"
    CIBW_BEFORE_BUILD_WINDOWS="if [ ! -f built-lib-$PYTHON_ARCH]; then make && make install && touch built-lib-$PYTHON_ARCH; fi"

I'd call this `CIBW_BEFORE_BUILD_FOR_EACH_ARCH` - if such a feature was implemented your option you would just need `CIBW_BEFORE_BUILD_FOR_EACH_ARCH="make && make install"`. PRs welcome, if you fancy trying an implementation - it should be pretty simple :)

**Comment by cbrown1** [comment]
Thanks. The name you suggest would be difficult to interpret by someone who doesn't know it. How about: CIBW_AFTER_IMAGE_START

Thanks. I will go with your suggested work around for now.

**Comment by joerick** [comment]
I agree, the name i suggested is a little cumbersome. But this will run twice within the same image on windows, so it's really for each architecture.

**Comment by McSinyx** [comment]
What is the current status for this?  Also is there anyway to load a script in the case of really really long list of commands?

**Comment by joerick** [comment]
It doesn't seem to have been a super popular request, but happy to take a look at a PR if anyone is interested in writing one? Still struggling to get a good name for it, though.

You can call out to a script, yes. If you had a script in your repo at `scripts/before-wheel-build`, just call it you would at a shell e.g.

```yaml
CIBW_BEFORE_BUILD: "scripts/before-wheel-build"
# or
CIBW_BEFORE_BUILD: "bash scripts/before-wheel-build.sh"
# or
CIBW_BEFORE_BUILD: "python scripts/before-wheel-build.py"
```

I should add an example of that to the docs, in fact.
