### ISSUE TITLE
How to access current python version from Test command?

### ISSUE THREAD

**Issue by jr-garcia** [joerick/cibuildwheel#56]
For the command: 
```yaml
- CIBW_TEST_COMMAND="{python} -m unittest {project}/tests/test_simple"
```
I'm getting ```KeyError: 'python'```

How do I access current python version, like in CIBW_BEFORE_BUILD?
Thank you.

**Comment by YannickJadoul** [comment]
Currently, that pattern is not being replaced by cibuildwheel in `CIBW_TEST_COMMAND`. Could you just use `python` instead, or does that result in problems?
If necessary, I could quickly write a PR that applies this formatting for `CIBW_TEST_COMMAND` as well. I can't see how that would break things.

**Comment by jr-garcia** [comment]
So far, I have not found problems using raw ```python``` word. However, for consistency, I think it would be good to provide the pattern replacement, maybe, in all commands.

**Comment by YannickJadoul** [comment]
Fair enough, I think it is a good point indeed. Thanks for noting and reporting!
I can have a look at it to make a PR, but if you get things working, at least it's not thát urgent.

**Comment by YannickJadoul** [comment]
I have a PR fixing this inconsistency in #59. If you are interested in having a look (and maybe getting rid of other, related inconsistencies we've overlooked), feel free to review!

**Comment by jr-garcia** [comment]
Thanks. Can't check for now, but feel free to close this if you think it works.

**Comment by YannickJadoul** [comment]
Closing this, now. Feel free to re-open if there's still a problem.
(FYI: there's also still a PR pending, #60, where we're actually getting rid of the replacement to just allow `python` and `pip` to be written.)
