### ISSUE TITLE
Support manylinux_2_24

### ISSUE THREAD

**Issue by mattip** [joerick/cibuildwheel#611]
Docker images with manylinux_2_24, based on Debian9, are up. It would be nice if cibuildwheel would support it. Note this requires moving from `yum` to `apt`.

**Comment by joerick** [comment]
Way ahead of ya @mattip - v1.10 has manylinux_2_24 support :) https://github.com/joerick/cibuildwheel/releases/tag/v1.10.0

**Comment by mattip** [comment]
Cool! Closing then. I see someone marked it done in pypa/manylinux#542, thanks.

**Comment by mattip** [comment]
Question, if you already thought about this: manylinux2014 and before are based on CentOS, manylinux_2_24 is based on debian. How do you approach installing from yum or apt appropriately?

**Comment by joerick** [comment]
We don't install anything from yum or apt ourselves, so we haven't hit that. Do you mean for sharing configs/scripts between manylinux20xx and manylinux_2_24?

**Comment by Czaki** [comment]
I think that share is hard or even impossible. Packages names differ between RedHat family and Debian one.

**Comment by mattip** [comment]
So if a project wants to build both manylinux2010 and manylinux_2_24 wheels, and wants to share as much infrastructure as possible, what do they do?

**Comment by henryiii** [comment]
Well, you already have to make a matrix with the manylinux setting; you should also include CIBW_BEFORE_BUILD in that matrix, and have a yum setup and an apt setup. Or build everything yourself and use only other PyPI deps in pyproject.toml. :)

`manylinux_2_24` is stuck with GCC 6, by the way - 2010 has GCC 8, and 2014 has GCC 9. If someone wants to help setup newer GCC builds, help appreciated. ;)
