### ISSUE TITLE
Apple Silicon in CIBW_BEFORE_BUILD

### ISSUE THREAD

**Issue by henryiii** [joerick/cibuildwheel#618]
Should the "Apple Silicon" environment variables be set in CIBW_BEFORE_BUILD? Currently, I don't think they are (but could be wrong). See https://github.com/pymupdf/PyMuPDF/discussions/875#discussioncomment-457205 . Might not be possible to set generally enough?

**Comment by joerick** [comment]
The 'Apple Silicon' variables - I guess that's `_PYTHON_HOST_PLATFORM`, `ARCHFLAGS` and `SDKROOT` - are evaluated in `setup_python`, so they are set in BEFORE_BUILD. They aren't set in BEFORE_ALL, though, because they depend on the specific build that we're doing.
