### ISSUE TITLE
NonPlatformWheelError: Build failed because a pure Python wheel was generated.

### ISSUE THREAD

**Issue by cryptocoinserver** [joerick/cibuildwheel#628]
I get a strange error, and didn't find much about it:

```
Building wheel for jesse-live (setup.py): finished with status 'done'
  Created wheel for jesse-live: filename=jesse_live-0.0.1-py3-none-any.whl size=30678 sha256=fc5dd4af5d0e4f92bd7634303a91bd051c2629fa7c8831bb3b995e2454804c1f
  Stored in directory: /Users/travis/Library/Caches/pip/wheels/ef/c2/15/402ce2c132b5e90021b8f59b35623772cbeb2fca42199cfc39
Successfully built jesse-live
Removed build tracker: '/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-req-tracker-4c_aa589'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/cibuildwheel/__main__.py", line 378, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/cibuildwheel/__main__.py", line 292, in main
    cibuildwheel.macos.build(build_options)
  File "/usr/local/lib/python3.7/site-packages/cibuildwheel/macos.py", line 337, in build
    raise NonPlatformWheelError()
cibuildwheel.util.NonPlatformWheelError: 
cibuildwheel: Build failed because a pure Python wheel was generated.
```

We have modified setup.py. Could this be the cause? We want to exclude the actual source code from the wheel so we cythonize the .py files.

```
import os
import sysconfig

from setuptools import setup, find_packages
from setuptools.command.build_py import build_py as _build_py

from Cython.Build import cythonize


EXCLUDE_FILES = [
    'live/__init__.py',
]


def get_ext_paths(root_dir, exclude_files):
    paths = []

    for root, dirs, files in os.walk(root_dir):
        for filename in files:
            if os.path.splitext(filename)[1] != '.py':
                continue

            file_path = os.path.join(root, filename)
            if file_path in exclude_files:
                continue

            paths.append(file_path)
    return paths


class build_py(_build_py):
    def find_package_modules(self, package, package_dir):
        ext_suffix = sysconfig.get_config_var('EXT_SUFFIX')
        modules = super().find_package_modules(package, package_dir)
        filtered_modules = []
        for (pkg, mod, filepath) in modules:
            if os.path.exists(filepath.replace('.py', ext_suffix)):
                continue
            filtered_modules.append((pkg, mod, filepath, ))
        return filtered_modules


setup(
    name='jesse-live',
    version='0.0.1',
    packages=find_packages(),
    ext_modules=cythonize(
        get_ext_paths('live', EXCLUDE_FILES),
        compiler_directives={'language_level': 3}
    ),
    cmdclass={
        'build_py': build_py
    }
)
```

Thank you.

**Comment by YannickJadoul** [comment]
@cryptocoinserver For some reason, your build/`setup.py` is generating the `jesse_live-0.0.1-py3-none-any.whl` wheel, with a filename that indicates it's works on all Python 3 version (i.e., doesn't contain any compiled extensions).
So the first step would be to figure out whether the file name is wrong and there's actually compiled extensions in there, or whether something goes wrong compiling things. Maybe you could check locally what `pip wheel` produces?

**Comment by henryiii** [comment]
You don't need cythonize, setuptools has natively supported Cython for 6 years or so now.

**Comment by henryiii** [comment]
Also, `pyx` files are never included in a wheel if I remember correctly?

**Comment by henryiii** [comment]
If you'd named your files .py, pretty sure Cythonize will not be picking them up, so there won't be an extension.

**Comment by cryptocoinserver** [comment]
Thanks. Fixed it. The directory was wrong. "live" should have been "jesse_live". So our fault. Good tip checking the wheel locally.
Thank you for the help!

@henryiii 
Yeah that's the reason we have a custom build_py.
All the python code is cythonized that way and protected. [Here ](https://medium.com/swlh/distributing-python-packages-protected-with-cython-40fc29d84caf) more about it, if you are interested.

**Comment by henryiii** [comment]
I guess you leave the .py names to make development easier? Otherwise, .pyx would do exactly the same thing, I think, not requiring any custom setup.py code beyond a normal extension. I'm about 70% sure `.pyx` files do not get added to the final wheel (as long as you don't set `include_package_data`). Plus that way you can see the hidden files vs. normal files directly in source. Glad you found the problem quickly :)
