### ISSUE TITLE
Strange behaviour when building wheel

### ISSUE THREAD

**Issue by SantoSimone** [joerick/cibuildwheel#632]
Hi, I am trying to use cibuildwheel to be able to create a wheel for macOS in my repo. To test how this works i created a simple repo example that follows [this](https://stackoverflow.com/a/47651621/14321417) and can be found [here](https://github.com/SantoSimone/cmake_example).
As it can be seen in the "Actions" tab, the wheel building fails with 
`"cibuildwheel: Build failed because a pure Python wheel was generated."`
But I have a strange behaviour in other situations:
- Local machine (Win10): 
- 1. if I use `pip wheel . -w ./dist" the output is `cmake_example-0.0.1-py3-none-any.whl`
- 2. if I use `python setup.py bdist_wheel` the output is `cmake_example-0.0.1-cp38-cp38-win_amd64.whl` (which is what I expected) but the command ends strangely
```running bdist_wheel
running build
running build_py
copying cmake_example\math.py -> build\lib.win-amd64-3.8\cmake_example
running build_ext
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- pybind11 v2.6.1
-- Found PythonInterp: C:/Users/sismo/AppData/Local/Programs/Python/Python38/python.exe (found version "3.8.2")
-- Found PythonLibs: C:/Users/sismo/AppData/Local/Programs/Python/Python38/libs/python38.lib
-- Configuring done
-- Generating done
-- Build files have been written to: D:/DVC/projects/luxottica/test_python_wheel/_dvc_code/so_remake/cmake_example/build/temp.win-amd64-3.8/Release
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  _math.vcxproj -> D:\DVC\projects\luxottica\test_python_wheel\_dvc_code\so_remake\cmake_example\build\lib.win-amd64-3.8\cmake_example\_math.cp38-win_amd64.pyd
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\cmake_example
copying build\lib.win-amd64-3.8\cmake_example\math.py -> build\bdist.win-amd64\wheel\.\cmake_example
copying build\lib.win-amd64-3.8\cmake_example\_math.cp38-win_amd64.pyd -> build\bdist.win-amd64\wheel\.\cmake_example
copying build\lib.win-amd64-3.8\cmake_example\__init__.py -> build\bdist.win-amd64\wheel\.\cmake_example
running install_egg_info
running egg_info
writing cmake_example.egg-info\PKG-INFO
writing dependency_links to cmake_example.egg-info\dependency_links.txt
writing top-level names to cmake_example.egg-info\top_level.txt
reading manifest file 'cmake_example.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cmake_example.egg-info\SOURCES.txt'
Copying cmake_example.egg-info to build\bdist.win-amd64\wheel\.\cmake_example-0.0.1-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build\bdist.win-amd64\wheel\cmake_example-0.0.1.dist-info\WHEEL
creating 'dist\cmake_example-0.0.1-cp38-cp38-win_amd64.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'cmake_example/__init__.py'
adding 'cmake_example/_math.cp38-win_amd64.pyd'
adding 'cmake_example/math.py'
adding 'cmake_example-0.0.1.dist-info/LICENSE'
adding 'cmake_example-0.0.1.dist-info/METADATA'
adding 'cmake_example-0.0.1.dist-info/WHEEL'
adding 'cmake_example-0.0.1.dist-info/top_level.txt'
adding 'cmake_example-0.0.1.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
C:\Users\sismo\AppData\Local\Programs\Python\Python38\lib\site-packages\wheel\bdist_wheel.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  if get_flag('Py_DEBUG',
```

- Remote machine (Ubuntu): no matter what I use, the output is `cmake_example-0.0.1-cp36-cp36m-linux_x86_64.whl` (as expected)

I think there should be at least 2 problems: one is causing my local machine to fail one of the two wheels, one is causing the "github" wheel to fail into a pure-python wheel.
Any thoughts?

**Comment by YannickJadoul** [comment]
What's the output of a failed `pip wheel` run (potentially adding `-v` or `-vv` to get more output)? And what the content of that wheel (it's just a zip file in disguise) ?

You do have this "let's ignore all errors" at the end of your `setup.py`, so... you might unknowingly be ignoring an error?

```py
try:
    setup(**kwargs)        
except:
    print('Failed to build extension!')
    del kwargs['ext_modules']
    setup(**kwargs)
```

**Comment by henryiii** [comment]
That doesn't even print the error that failed! Also, _never_ use a raw except. At the very least, use `except BaseException:`, and in your case, `except BaseException as e` then print `e`. Your raw except will catch `Control C`! And memory errors. Etc.

Also, CMake 3.4 should be the minimum CMake version, not 2.8 (that's 13 years old, older than C++11!). Setting it that low will cause issues such as on macOS. If you use pybind11, pybind11's CMake files are 3.4+.

**Comment by YannickJadoul** [comment]
> Your raw except will catch `Control C`! And memory errors. Etc.

`BaseException` still catches that as well, though?

```pycon
>>> KeyboardInterrupt.__bases__
(<class 'BaseException'>,)
```

**Comment by henryiii** [comment]
Sorry! I had it backwards. You should do `Exception`, not `BaseException`. Catching `BaseException` is just like a raw `except:` except that it's explicit in showing that you really do want to catch things like KeyboardInterrupt. 95% of the time, you want to catch no more than `Exception`, and if you can be more specific (the failure is likely 1-2 specific errors), then that's even better.

**Comment by YannickJadoul** [comment]
Now I totally agree, yes :-) I looked it up, and Python's docs say that raw `except` is catching everything:

> An expression-less except clause, if present, must be last; it matches any exception.

(https://docs.python.org/3/reference/compound_stmts.html#except)

However, you can't `raise` anything that's not a `BaseException`, so let's just say it's completely equivalent to `except BaseException`?

```pycon
>>> raise 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```

**Comment by Czaki** [comment]
> However, you can't `raise` anything that's not a `BaseException`, so let's just say it's completely equivalent to `except BaseException`?

If I good remember python 2 allow to raise int. And these docs about catching everything comes from Python 2. 

@SantoSimone For debug I suggest to remove `try ... except ...`  clause for fast got error information. 

The main difference between `pip wheel`  and `setup.py bdist_wheel` is that `pip wheel` performs build using a copy of project inside `tmp` directory and `setup.py bdist_wheel` perform its locally. Maybe there is a problem with the path of building extensions.

**Comment by henryiii** [comment]
> If I good remember python 2 allow to raise int.

Close! Python 2 allowed raising an old-style class as an exception. Not int, though. Those are now gone in Python 3.

```
WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Dec 21 2020, 23:00:36)
[GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> raise 23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not int
```

Pip wheel should make an SDist as part of the procedure, as well, while bdist_wheel will only perform the build step, so if you are missing files from MANIFEST.in, that would likely only show up in the pip wheel command (this is using `build_meta` rather than `__legacy__`); but everything seems to be in order, that's the first thing I checked.

**Comment by SantoSimone** [comment]
Oh, I did not put attention to that `try .. except` block! After removing I found that i had some problems with pybind11's commit referenced in my project.
Thank you all for being so fast in answering!
