### ISSUE TITLE
Add support for manylinux2010

### ISSUE THREAD

**Issue by mayeut** [joerick/cibuildwheel#65]
Add support for manylinux2010

c.f. pypa/manylinux#179

**Comment by joerick** [comment]
So I'm guessing we'll add this as a separate python configuration, alongside manylinux1?

**Comment by YannickJadoul** [comment]
Seems manylinux2010 is almost ready, so we could start experimenting with how to add it to cibuildwheel. I'm quite happy/eager to play around with it a bit, if I find time, so I'll see if I can make a PR, soon :-)

@joerick What exactly did you mean/have in mind, here?

> So I'm guessing we'll add this as a separate python configuration, alongside manylinux1?

Something that can be matched by `CIBW_BUILD` and `CIBW_SKIP`?

**Comment by joerick** [comment]
> Something that can be matched by CIBW_BUILD and CIBW_SKIP?

This was my initial guess, yes

**Comment by hameerabbasi** [comment]
I ran into needing this for my project, see: Quansight-Labs/uarray#193

**Comment by mayeut** [comment]
Cross-Reference #155

**Comment by jlaine** [comment]
It looks like manylinux2010 is now officially supported and there are wheel on PyPI. What's needed to add support to cibuildwheel?

**Comment by YannickJadoul** [comment]
@jlaine, #155 adds `manylinux2010` support and is ready to be merged.
But given that this will be a new release, deprecating some old options, I had the impression @joerick wanted to still merge some other PRs before releasing?

**Comment by joerick** [comment]
Fixed in #155, release should be soon!
