### ISSUE TITLE
Capitalisation issues with CMake and correct python version discovery. 

### ISSUE THREAD

**Issue by cheesema** [joerick/cibuildwheel#667]
Thanks for this awesome package :)

Using cmake >1.18, I was not getting correct python detection on Windows and OSX builds using travis. (on this branch here: https://github.com/AdaptiveParticles/PyLibAPR/tree/ci_build)

```
###############################################################################
# Python wrappers
###############################################################################
message(STATUS "PyAPR: Building PYTHON wrappers")

set(PYBIND11_PYTHON_VERSION 3)

set(Python_EXECUTABLE "${PYTHON_EXECUTABLE}") 
set(Python_INCLUDE_DIR "${PYTHON_INCLUDE_DIR}")
unset(PYTHON_EXECUTABLE)
unset(PYTHON_INCLUDE_DIR)
unset(PYTHON_LIBRARY)
unset(PYTHON_VERSION_STRING)

if(${CMAKE_VERSION} VERSION_LESS "3.18.0") #detection syntax changed
    find_package( PythonInterp ${PYTHON_VERSION} REQUIRED )
    find_package( PythonLibs ${PYTHON_VERSION} REQUIRED )
else()
    find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
endif()
``` 

From diving into https://github.com/YannickJadoul/Parselmouth I got the above fix required in the cmake file to make this work across platforms. 

Seemingly arising from the input at these steps of passing the python executable version into the cmake calls:

:  ['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/z3/_825pg0s3jvf0hb_q8kzmg5h0000gn/T/pip-req-build-jndjrwlx/build/lib.macosx-10.9-x86_64-3.6/', '-DPYTHON_EXECUTABLE=/private/tmp/cibw_bin/python', '-DCMAKE_BUILD_TYPE=Release']

Which when set to the Python version instead of PYTHON as in the above then work correclty. 

Not sure if you are aware of the above, and whether this could be easily fixed. Apologies for not tracing down the offending lines in your lib.

**Comment by YannickJadoul** [comment]
@cheesema That's slightly weird. But I think part of the confusion comes from mixing the old and new FindPython CMake modules (the old one uses `PYTHON`, the new one `Python`). But anyway, I think the new version is already from CMake 3 or so? So `if(${CMAKE_VERSION} VERSION_LESS "3.18.0")` is way to late to switch, I think.

At any rate, this isn't really related to cibuildwheel in any way. cibuildwheel doesn't touch CMake, and it's documented that on Windows and macOS you're running in the existing environment.

I'll tag @henryiii, who knows a lot more about CMake and might have some more tips and tricks for you (apart from his great, but probably too generic tutorial on Modern CMake: https://cliutils.gitlab.io/modern-cmake/), but I'll also close this as not really related to cibuildwheel.

**Comment by cheesema** [comment]
Yes, apologies this was me being lazy and not following through to check my own code, indeed just in my own setup.py file that had the capitalisation issue. CIBuildwheel just highlighted that this was not working correctly on Windows and OSX.

**Comment by YannickJadoul** [comment]
No problem! Thanks for reporting, but I'm not sure where we'd need to add this to the cibuildwheel docs, to be honest.
