### ISSUE TITLE
Python 3.8 for win32 producing amd64 wheel

### ISSUE THREAD

**Issue by bryan-hunt** [joerick/cibuildwheel#670]
So I encountered a weird situation trying to update my github actions where it creating an amd64 wheel for python3.8 x86 under windows. This then causes the amd64 build to fail since the wheel already exists. Python 3.6 and 3.7 built correctly.

[7_Build wheels.txt](https://github.com/joerick/cibuildwheel/files/6466625/7_Build.wheels.txt)

**Comment by joerick** [comment]
Hi! Could you post a link to the code (specifically the commit)  that produced this log?

By the way, this looks suspicious in your log:

> C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-y92w6kzv\setup.py:45: SyntaxWarning: "is" with a literal. Did you mean "=="?
2021-05-12T00:56:57.2580986Z       if sys.platform is 'win32':

**Comment by bryan-hunt** [comment]
I did make a correction that error - it merely adds the dll to the package_data and doesn't impact the build itself.

Here is the configuration file that triggered the build that failed: https://github.com/MicrochipTech/cryptoauthlib/blob/84cd6d5e4aa8add1dfb189dd19d61df3d2062a45/.github/workflows/build.yml

**Comment by henryiii** [comment]
Doesn't:
```
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
```
Need to be be done once per arch? It defaults to 64-bit, which is why you built 64 bit wheels both times, I think.

**Comment by henryiii** [comment]
What happens if you don't have this step? You can also remove the setup-python step, as it's unused.

**Comment by bryan-hunt** [comment]
> Doesn't:
> 
> ```yaml
> - name: Enable Developer Command Prompt
>   uses: ilammy/msvc-dev-cmd@v1
> ```
> 
> Need to be be done once per arch? It defaults to 64-bit, which is why you built 64 bit wheels both times, I think.
> 
> ```yaml
> with:
>   arch: x64
> ```
> 
> is the default.

Doesn't explain 3.6 and 3.7 works but 3.8 fails.

> What happens if you don't have this step? You can also remove the setup-python step, as it's unused.

I'll give it a try.

**Comment by bryan-hunt** [comment]
Okay I ran through with both of these steps removed and everything executed properly. Why 3.6 and 3.7 work differently who knows but cmake is still finding the proper compilers without the developer command prompt action so all of our needs are satisfied.

Thanks for the assistance!

**Comment by Czaki** [comment]
they may use different mechanism of detecting target architecture.
