### ISSUE TITLE
'wheel' missing from setup.py install_requires list?

### ISSUE THREAD

**Issue by miguelsousa** [joerick/cibuildwheel#87]
While trying to use a vanilla cibuildwheel configuration with AppVeyor, I kept running into this error,
```
cibuildwheel: Failed to get name of the package. Command was ['c:\\python27\\python.exe', '.\\setup.py', '--name']
```

It was only after running that command (`python .\\setup.py --name`) ahead of the `cibuildwheel --output-dir wheelhouse` that I finally got a clue of what was going on,
```
setup requires that the Python package 'wheel' be installed. Try the command 'pip install wheel'.
```

To resolve this problem I've added `'wheel'` to [setup.py `install_requires` list](https://github.com/joerick/cibuildwheel/blob/master/setup.py#L12) in our fork.

I think that two changes are necessary:
1. On [line 111 of `__main__.py`](https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/__main__.py#L111), print the **`output`** of [CalledProcessError](https://docs.python.org/2/library/subprocess.html#subprocess.CalledProcessError), and exit with the value of **`returncode`**.
2. Add `'wheel'` to [setup.py `install_requires` list](https://github.com/joerick/cibuildwheel/blob/master/setup.py#L12)

Do you want a PR?

**Comment by joerick** [comment]
Hey miguelsousa! Thanks for the debugging. Would love a PR for [1] above. Regarding [2], can you see where that error message is coming from? Perhaps there's something about your project's `setup.py` that requires it?

**Comment by miguelsousa** [comment]
@joerick You were quite right about our `setup.py`; the `wheel` requirement come from it.
PR #88 is in.
