### ISSUE TITLE
[question] cibuildwheel generates larger Windows wheel files

### ISSUE THREAD

**Issue by miguelsousa** [joerick/cibuildwheel#89]
We've just finished transitioning our repository ([afdko](https://github.com/adobe-type-tools/afdko)) to using **cibuildwheel**. The process of building and testing the wheels is now much simple — thank you! — but for some reason the file size of the Windows wheel is now noticeably larger (2.65 MB → 3.76 MB). Our wheels contain both Python-based tools and C-based tools (not Python extensions). The binaries of the latter is what grew. Generating the wheel on a local machine also yields a size comparable to the cibuildwheel output.

In our quest to understand the cause of the size difference, we compared build logs, environment variables, and even the hex data of the binaries themselves, to no avail.

We're out of ideas, so if anyone has a clue of why the Windows wheel file is larger, please share.
Thank you.

--

Before cibuildwheel config:
* [wheels (v2.7.3a5)](https://github.com/adobe-type-tools/afdko/releases/tag/2.7.3a5)
* [appveyor.yml](https://github.com/adobe-type-tools/afdko/blob/5e1b24b1d178289a091517975d1ed0814b2b905d/.appveyor.yml)

After cibuildwheel config:
* [wheels (v2.7.3b0)](https://github.com/adobe-type-tools/afdko/releases/tag/2.7.3b0)
* [appveyor.yml](https://github.com/adobe-type-tools/afdko/blob/2.7.3b0/.appveyor.yml)

**Comment by cher-nov** [comment]
Hi. Did you try to open both wheels in an archiver (they're simple **.zip** files actually) and manually compare their contents by yourself?

**Comment by miguelsousa** [comment]
@cher-nov yes. They seemed like a bunch of differences related to localization.

**Comment by YannickJadoul** [comment]
Could it have something to do with the [`appveyor_run_with_env.cmd`](https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/resources/appveyor_run_with_env.cmd) file? This script is trying to set the right C/C++ compilers that match how the Windows CPython executables were compiled.

Sorry this never got resolved, btw :-/

**Comment by miguelsousa** [comment]
Figured it out (I think). The larger wheel file is caused by initializing the build environment as 64bit. When it's initialized as 32bit —by using `call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"`— the wheel file has a smaller size.

(WOW, couldn't stop noticing that the first comment was exactly 1 year ago)

**Comment by YannickJadoul** [comment]
Huh!?
Hmmm, something to do with alignment, then, or so? I know that 64-bit programs tend to take up more memory, but ...

Anyway, you found it. That's the most important thing, I guess. Thanks for letting us know!
