### ISSUE TITLE
CircleCI support

### ISSUE THREAD

**Issue by altendky** [joerick/cibuildwheel#90]
I'm setting up [Twisted](https://twistedmatrix.com/) with `cibuildwheel` over in twisted/twisted#1051.  I haven't really tested anything but I got Windows wheels building on AppVeyor and Linux wheels on Travis so far.  Next step? CircleCI for OSX wheels...  Before I dive in, any comments on any other efforts to do this?  Interest in trying to do some of the work?  Suggestions how I get started?  I honestly haven't done anything quite yet but I like to raise the topic publicly first in case there's advice or opinions worth sharing.

Cheers,
-kyle

P.S. Thanks so much for cibuildwheel, it certainly made this all go a lot quicker so far.

**Comment by joerick** [comment]
Thanks Kyle! I'll reply to the PR.

**Comment by altendky** [comment]
More work can certainly be done but this CircleCI is working.
