### ISSUE TITLE
Add CIBW_BUILD as correlary to CIBW_SKIP (and cli option)

### ISSUE THREAD

**Issue by altendky** [joerick/cibuildwheel#98]
Presently the build list  is effectively everything supported.  It'd be nice to be able to easily request a single wheel build to fit into CI schemes with a build per Python version.  This is coming up in my Twisted PR's as I try to set it up to run all tests against the built wheels.  Travis doesn't save artifacts or even files between jobs (without using external storage accounts) so I'm shooting for building in the individual job.

I would expect the built items to be effectively the `set(CIBW_BUILD) - set(CIBW_SKIP)`.

Of course there we'll be some overhead to spinning up docker more times.  We'll see what that is after I get my PR working.  twisted/twisted#1067

I might work on this soon, I might not.  We'll see...  :]

**Comment by altendky** [comment]
@YannickJadoul if you want to take it on, go for it.  :]  Though if there's interest in subcommands it might be worth switching over to click instead first.  I personally use click for all my CLI's unless I'm trying to make a bootstrap sort of script.

**Comment by astrofrog** [comment]
I'd really like to see this feature too!

**Comment by joerick** [comment]
PRs welcome! :D

**Comment by YannickJadoul** [comment]
PR's there!

> Though if there's interest in subcommands it might be worth switching over to click instead first.

I don't know what the actual plan is for subcommands? So for now I have just added this on the same level as `CIBW_SKIP`. But it was rather easy to fit into the current design (I'm still surprised by how easy it is to make these small changes to the code base!), so the PR shouldn't stop any further developments.

**Comment by altendky** [comment]
Thanks all. Released in 0.10.0.
